package com.ybh.front.mapper;

import com.ybh.front.model.CDNProductlist;
import com.ybh.front.model.CDNProductlistExample;
import com.ybh.front.model.CDNProductlistWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CDNProductlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_CDNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(CDNProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_CDNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(CDNProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_CDNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(CDNProductlistWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_CDNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(CDNProductlistWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_CDNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<CDNProductlistWithBLOBs> selectByExampleWithBLOBs(CDNProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_CDNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<CDNProductlist> selectByExample(CDNProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_CDNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") CDNProductlistWithBLOBs record, @Param("example") CDNProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_CDNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CDNProductlistWithBLOBs record, @Param("example") CDNProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_CDNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") CDNProductlist record, @Param("example") CDNProductlistExample example);
}