package com.ybh.front.mapper;

import com.ybh.front.model.DomainProductlist;
import com.ybh.front.model.DomainProductlistExample;
import com.ybh.front.model.DomainProductlistWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DomainProductlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_DomainProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(DomainProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_DomainProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(DomainProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_DomainProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(DomainProductlistWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_DomainProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(DomainProductlistWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_DomainProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<DomainProductlistWithBLOBs> selectByExampleWithBLOBs(DomainProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_DomainProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<DomainProductlist> selectByExample(DomainProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_DomainProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") DomainProductlistWithBLOBs record, @Param("example") DomainProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_DomainProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") DomainProductlistWithBLOBs record, @Param("example") DomainProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_DomainProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") DomainProductlist record, @Param("example") DomainProductlistExample example);
}