package com.ybh.front.mapper;

import com.ybh.front.model.HtmlStyle;
import com.ybh.front.model.HtmlStyleExample;
import com.ybh.front.model.HtmlStyleWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HtmlStyleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_HtmlStyle
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(HtmlStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_HtmlStyle
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(HtmlStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_HtmlStyle
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(HtmlStyleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_HtmlStyle
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(HtmlStyleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_HtmlStyle
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<HtmlStyleWithBLOBs> selectByExampleWithBLOBs(HtmlStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_HtmlStyle
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<HtmlStyle> selectByExample(HtmlStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_HtmlStyle
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") HtmlStyleWithBLOBs record, @Param("example") HtmlStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_HtmlStyle
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") HtmlStyleWithBLOBs record, @Param("example") HtmlStyleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_HtmlStyle
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") HtmlStyle record, @Param("example") HtmlStyleExample example);
}