package com.ybh.front.mapper;

import com.ybh.front.model.IDCProductlist;
import com.ybh.front.model.IDCProductlistExample;
import com.ybh.front.model.IDCProductlistWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IDCProductlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(IDCProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(IDCProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(IDCProductlistWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(IDCProductlistWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<IDCProductlistWithBLOBs> selectByExampleWithBLOBs(IDCProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<IDCProductlist> selectByExample(IDCProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") IDCProductlistWithBLOBs record, @Param("example") IDCProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") IDCProductlistWithBLOBs record, @Param("example") IDCProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") IDCProductlist record, @Param("example") IDCProductlistExample example);
}