package com.ybh.front.mapper;

import com.ybh.front.model.IDCProductlist_AGN;
import com.ybh.front.model.IDCProductlist_AGNExample;
import com.ybh.front.model.IDCProductlist_AGNWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IDCProductlist_AGNMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(IDCProductlist_AGNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(IDCProductlist_AGNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(IDCProductlist_AGNWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(IDCProductlist_AGNWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<IDCProductlist_AGNWithBLOBs> selectByExampleWithBLOBs(IDCProductlist_AGNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<IDCProductlist_AGN> selectByExample(IDCProductlist_AGNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") IDCProductlist_AGNWithBLOBs record, @Param("example") IDCProductlist_AGNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") IDCProductlist_AGNWithBLOBs record, @Param("example") IDCProductlist_AGNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") IDCProductlist_AGN record, @Param("example") IDCProductlist_AGNExample example);
}