package com.ybh.front.mapper;

import com.ybh.front.model.Moneylog;
import com.ybh.front.model.MoneylogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MoneylogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Moneylog
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(MoneylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Moneylog
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(MoneylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Moneylog
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(Moneylog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Moneylog
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(Moneylog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Moneylog
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<Moneylog> selectByExample(MoneylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Moneylog
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") Moneylog record, @Param("example") MoneylogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Moneylog
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") Moneylog record, @Param("example") MoneylogExample example);
}