package com.ybh.front.mapper;

import com.ybh.front.model.NetCNProductlist_AGN;
import com.ybh.front.model.NetCNProductlist_AGNExample;
import com.ybh.front.model.NetCNProductlist_AGNWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NetCNProductlist_AGNMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(NetCNProductlist_AGNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(NetCNProductlist_AGNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(NetCNProductlist_AGNWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(NetCNProductlist_AGNWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<NetCNProductlist_AGNWithBLOBs> selectByExampleWithBLOBs(NetCNProductlist_AGNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<NetCNProductlist_AGN> selectByExample(NetCNProductlist_AGNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") NetCNProductlist_AGNWithBLOBs record, @Param("example") NetCNProductlist_AGNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NetCNProductlist_AGNWithBLOBs record, @Param("example") NetCNProductlist_AGNExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") NetCNProductlist_AGN record, @Param("example") NetCNProductlist_AGNExample example);
}