package com.ybh.front.mapper;

import com.ybh.front.model.NetCNProductlist;
import com.ybh.front.model.NetCNProductlistExample;
import com.ybh.front.model.NetCNProductlistWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NetCNProductlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(NetCNProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(NetCNProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(NetCNProductlistWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(NetCNProductlistWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<NetCNProductlistWithBLOBs> selectByExampleWithBLOBs(NetCNProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<NetCNProductlist> selectByExample(NetCNProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") NetCNProductlistWithBLOBs record, @Param("example") NetCNProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NetCNProductlistWithBLOBs record, @Param("example") NetCNProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_NetCNProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") NetCNProductlist record, @Param("example") NetCNProductlistExample example);
}