package com.ybh.front.mapper;

import com.ybh.front.model.online_aws;
import com.ybh.front.model.online_awsExample;
import com.ybh.front.model.online_awsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface online_awsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_online_aws
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(online_awsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_online_aws
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(online_awsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_online_aws
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(online_awsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_online_aws
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(online_awsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_online_aws
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<online_awsWithBLOBs> selectByExampleWithBLOBs(online_awsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_online_aws
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<online_aws> selectByExample(online_awsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_online_aws
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") online_awsWithBLOBs record, @Param("example") online_awsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_online_aws
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") online_awsWithBLOBs record, @Param("example") online_awsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_online_aws
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") online_aws record, @Param("example") online_awsExample example);
}