package com.ybh.front.mapper;

import com.ybh.front.model.OtherProductlist;
import com.ybh.front.model.OtherProductlistExample;
import com.ybh.front.model.OtherProductlistWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OtherProductlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_OtherProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(OtherProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_OtherProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(OtherProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_OtherProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(OtherProductlistWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_OtherProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(OtherProductlistWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_OtherProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<OtherProductlistWithBLOBs> selectByExampleWithBLOBs(OtherProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_OtherProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<OtherProductlist> selectByExample(OtherProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_OtherProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") OtherProductlistWithBLOBs record, @Param("example") OtherProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_OtherProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") OtherProductlistWithBLOBs record, @Param("example") OtherProductlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_OtherProductlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") OtherProductlist record, @Param("example") OtherProductlistExample example);
}