package com.ybh.front.mapper;

import com.ybh.front.model.Product_Host;
import com.ybh.front.model.Product_HostExample;
import com.ybh.front.model.Product_HostWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Product_HostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Host
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(Product_HostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Host
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(Product_HostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Host
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(Product_HostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Host
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(Product_HostWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Host
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<Product_HostWithBLOBs> selectByExampleWithBLOBs(Product_HostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Host
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<Product_Host> selectByExample(Product_HostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Host
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") Product_HostWithBLOBs record, @Param("example") Product_HostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Host
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Product_HostWithBLOBs record, @Param("example") Product_HostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Host
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") Product_Host record, @Param("example") Product_HostExample example);
}