package com.ybh.front.mapper;

import com.ybh.front.model.Product_Other;
import com.ybh.front.model.Product_OtherExample;
import com.ybh.front.model.Product_OtherWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Product_OtherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Other
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(Product_OtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Other
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(Product_OtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Other
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(Product_OtherWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Other
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(Product_OtherWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Other
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<Product_OtherWithBLOBs> selectByExampleWithBLOBs(Product_OtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Other
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<Product_Other> selectByExample(Product_OtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Other
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") Product_OtherWithBLOBs record, @Param("example") Product_OtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Other
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Product_OtherWithBLOBs record, @Param("example") Product_OtherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_Other
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") Product_Other record, @Param("example") Product_OtherExample example);
}