package com.ybh.front.mapper;

import com.ybh.front.model.Product_VPS_ACL;
import com.ybh.front.model.Product_VPS_ACLExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Product_VPS_ACLMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_VPS_ACL
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(Product_VPS_ACLExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_VPS_ACL
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(Product_VPS_ACLExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_VPS_ACL
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(Product_VPS_ACL record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_VPS_ACL
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(Product_VPS_ACL record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_VPS_ACL
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<Product_VPS_ACL> selectByExample(Product_VPS_ACLExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_VPS_ACL
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") Product_VPS_ACL record, @Param("example") Product_VPS_ACLExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Product_VPS_ACL
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") Product_VPS_ACL record, @Param("example") Product_VPS_ACLExample example);
}