package com.ybh.front.mapper;

import com.ybh.front.model.ServerVPSlist;
import com.ybh.front.model.ServerVPSlistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ServerVPSlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_ServerVPSlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    long countByExample(ServerVPSlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_ServerVPSlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int deleteByExample(ServerVPSlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_ServerVPSlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insert(ServerVPSlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_ServerVPSlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int insertSelective(ServerVPSlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_ServerVPSlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    List<ServerVPSlist> selectByExample(ServerVPSlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_ServerVPSlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") ServerVPSlist record, @Param("example") ServerVPSlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_ServerVPSlist
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    int updateByExample(@Param("record") ServerVPSlist record, @Param("example") ServerVPSlistExample example);
}