package com.ybh.front.model;

public class AgentWithBLOBs extends Agent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Agent.beianfile
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private byte[] beianfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Agent.emailendmessage
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String emailendmessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Agent.upgif
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private byte[] upgif;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Agent.beianfile
     *
     * @return the value of FreeHost_Agent.beianfile
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public byte[] getBeianfile() {
        return beianfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Agent.beianfile
     *
     * @param beianfile the value for FreeHost_Agent.beianfile
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setBeianfile(byte[] beianfile) {
        this.beianfile = beianfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Agent.emailendmessage
     *
     * @return the value of FreeHost_Agent.emailendmessage
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getEmailendmessage() {
        return emailendmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Agent.emailendmessage
     *
     * @param emailendmessage the value for FreeHost_Agent.emailendmessage
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setEmailendmessage(String emailendmessage) {
        this.emailendmessage = emailendmessage == null ? null : emailendmessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Agent.upgif
     *
     * @return the value of FreeHost_Agent.upgif
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public byte[] getUpgif() {
        return upgif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Agent.upgif
     *
     * @param upgif the value for FreeHost_Agent.upgif
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUpgif(byte[] upgif) {
        this.upgif = upgif;
    }
}