package com.ybh.front.model;

public class CDNProductlist_AGN {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_CDNProductlist_AGN.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_CDNProductlist_AGN.CDNtype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String cdntype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_CDNProductlist_AGN.usermoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Double usermoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_CDNProductlist_AGN.html
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String html;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_CDNProductlist_AGN.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_CDNProductlist_AGN.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_CDNProductlist_AGN.id
     *
     * @return the value of FreeHost_CDNProductlist_AGN.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_CDNProductlist_AGN.id
     *
     * @param id the value for FreeHost_CDNProductlist_AGN.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_CDNProductlist_AGN.CDNtype
     *
     * @return the value of FreeHost_CDNProductlist_AGN.CDNtype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCdntype() {
        return cdntype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_CDNProductlist_AGN.CDNtype
     *
     * @param cdntype the value for FreeHost_CDNProductlist_AGN.CDNtype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCdntype(String cdntype) {
        this.cdntype = cdntype == null ? null : cdntype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_CDNProductlist_AGN.usermoney
     *
     * @return the value of FreeHost_CDNProductlist_AGN.usermoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Double getUsermoney() {
        return usermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_CDNProductlist_AGN.usermoney
     *
     * @param usermoney the value for FreeHost_CDNProductlist_AGN.usermoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUsermoney(Double usermoney) {
        this.usermoney = usermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_CDNProductlist_AGN.html
     *
     * @return the value of FreeHost_CDNProductlist_AGN.html
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getHtml() {
        return html;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_CDNProductlist_AGN.html
     *
     * @param html the value for FreeHost_CDNProductlist_AGN.html
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setHtml(String html) {
        this.html = html == null ? null : html.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_CDNProductlist_AGN.agent1
     *
     * @return the value of FreeHost_CDNProductlist_AGN.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent1() {
        return agent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_CDNProductlist_AGN.agent1
     *
     * @param agent1 the value for FreeHost_CDNProductlist_AGN.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent1(String agent1) {
        this.agent1 = agent1 == null ? null : agent1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_CDNProductlist_AGN.agent2
     *
     * @return the value of FreeHost_CDNProductlist_AGN.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent2() {
        return agent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_CDNProductlist_AGN.agent2
     *
     * @param agent2 the value for FreeHost_CDNProductlist_AGN.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent2(String agent2) {
        this.agent2 = agent2 == null ? null : agent2.trim();
    }
}