package com.ybh.front.model;

import java.util.Date;

public class ICPDB {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_ICPDB.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_ICPDB.username
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_ICPDB.ftpname
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String ftpname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_ICPDB.domain
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_ICPDB.status
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_ICPDB.firstaddtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date firstaddtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_ICPDB.checktime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date checktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_ICPDB.ICP_SN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String icpSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_ICPDB.ICP_Who
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String icpWho;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_ICPDB.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_ICPDB.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_ICPDB.idimg
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private byte[] idimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_ICPDB.id
     *
     * @return the value of FreeHost_ICPDB.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_ICPDB.id
     *
     * @param id the value for FreeHost_ICPDB.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_ICPDB.username
     *
     * @return the value of FreeHost_ICPDB.username
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_ICPDB.username
     *
     * @param username the value for FreeHost_ICPDB.username
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_ICPDB.ftpname
     *
     * @return the value of FreeHost_ICPDB.ftpname
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getFtpname() {
        return ftpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_ICPDB.ftpname
     *
     * @param ftpname the value for FreeHost_ICPDB.ftpname
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setFtpname(String ftpname) {
        this.ftpname = ftpname == null ? null : ftpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_ICPDB.domain
     *
     * @return the value of FreeHost_ICPDB.domain
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_ICPDB.domain
     *
     * @param domain the value for FreeHost_ICPDB.domain
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_ICPDB.status
     *
     * @return the value of FreeHost_ICPDB.status
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_ICPDB.status
     *
     * @param status the value for FreeHost_ICPDB.status
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_ICPDB.firstaddtime
     *
     * @return the value of FreeHost_ICPDB.firstaddtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getFirstaddtime() {
        return firstaddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_ICPDB.firstaddtime
     *
     * @param firstaddtime the value for FreeHost_ICPDB.firstaddtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setFirstaddtime(Date firstaddtime) {
        this.firstaddtime = firstaddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_ICPDB.checktime
     *
     * @return the value of FreeHost_ICPDB.checktime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_ICPDB.checktime
     *
     * @param checktime the value for FreeHost_ICPDB.checktime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_ICPDB.ICP_SN
     *
     * @return the value of FreeHost_ICPDB.ICP_SN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getIcpSn() {
        return icpSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_ICPDB.ICP_SN
     *
     * @param icpSn the value for FreeHost_ICPDB.ICP_SN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setIcpSn(String icpSn) {
        this.icpSn = icpSn == null ? null : icpSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_ICPDB.ICP_Who
     *
     * @return the value of FreeHost_ICPDB.ICP_Who
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getIcpWho() {
        return icpWho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_ICPDB.ICP_Who
     *
     * @param icpWho the value for FreeHost_ICPDB.ICP_Who
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setIcpWho(String icpWho) {
        this.icpWho = icpWho == null ? null : icpWho.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_ICPDB.agent1
     *
     * @return the value of FreeHost_ICPDB.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent1() {
        return agent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_ICPDB.agent1
     *
     * @param agent1 the value for FreeHost_ICPDB.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent1(String agent1) {
        this.agent1 = agent1 == null ? null : agent1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_ICPDB.agent2
     *
     * @return the value of FreeHost_ICPDB.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent2() {
        return agent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_ICPDB.agent2
     *
     * @param agent2 the value for FreeHost_ICPDB.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent2(String agent2) {
        this.agent2 = agent2 == null ? null : agent2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_ICPDB.idimg
     *
     * @return the value of FreeHost_ICPDB.idimg
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public byte[] getIdimg() {
        return idimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_ICPDB.idimg
     *
     * @param idimg the value for FreeHost_ICPDB.idimg
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setIdimg(byte[] idimg) {
        this.idimg = idimg;
    }
}