package com.ybh.front.model;

import java.math.BigDecimal;

public class IDCProductlist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.IDCtype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String idctype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.istg
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Boolean istg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.usermoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal usermoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer serverlistid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.ServerlistID2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer serverlistid2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.ServerlistID3
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer serverlistid3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.ServerlistID4
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer serverlistid4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.ServerlistID5
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer serverlistid5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.canmonth
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canmonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.canhalfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canhalfyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.canbyenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canbyenduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.canbyagnenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canbyagnenduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.canbyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canbyagn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer orderbyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.canshowyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canshowyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.typeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.canseason
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canseason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.allowupdate
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String allowupdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.allowupdatetoother
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String allowupdatetoother;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.updatebytypeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String updatebytypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.price0
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal price0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.price1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal price1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.price2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal price2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.price3
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal price3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.price4
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal price4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.price5
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal price5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.price6
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal price6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.price7
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal price7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.price8
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal price8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.price9
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal price9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.price10
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal price10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.PAY_Month
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String payMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.PAY_Season
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String paySeason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.PAY_halfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String payHalfyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.PAY_Nextyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String payNextyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.PAY_2year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String pay2year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.PAY_3year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String pay3year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.PAY_4year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String pay4year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.PAY_5year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String pay5year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist.onlyusebyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String onlyusebyagn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.id
     *
     * @return the value of FreeHost_IDCProductlist.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.id
     *
     * @param id the value for FreeHost_IDCProductlist.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.IDCtype
     *
     * @return the value of FreeHost_IDCProductlist.IDCtype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getIdctype() {
        return idctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.IDCtype
     *
     * @param idctype the value for FreeHost_IDCProductlist.IDCtype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setIdctype(String idctype) {
        this.idctype = idctype == null ? null : idctype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.istg
     *
     * @return the value of FreeHost_IDCProductlist.istg
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Boolean getIstg() {
        return istg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.istg
     *
     * @param istg the value for FreeHost_IDCProductlist.istg
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setIstg(Boolean istg) {
        this.istg = istg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.usermoney
     *
     * @return the value of FreeHost_IDCProductlist.usermoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getUsermoney() {
        return usermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.usermoney
     *
     * @param usermoney the value for FreeHost_IDCProductlist.usermoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUsermoney(BigDecimal usermoney) {
        this.usermoney = usermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.ServerlistID
     *
     * @return the value of FreeHost_IDCProductlist.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getServerlistid() {
        return serverlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.ServerlistID
     *
     * @param serverlistid the value for FreeHost_IDCProductlist.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setServerlistid(Integer serverlistid) {
        this.serverlistid = serverlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.ServerlistID2
     *
     * @return the value of FreeHost_IDCProductlist.ServerlistID2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getServerlistid2() {
        return serverlistid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.ServerlistID2
     *
     * @param serverlistid2 the value for FreeHost_IDCProductlist.ServerlistID2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setServerlistid2(Integer serverlistid2) {
        this.serverlistid2 = serverlistid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.ServerlistID3
     *
     * @return the value of FreeHost_IDCProductlist.ServerlistID3
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getServerlistid3() {
        return serverlistid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.ServerlistID3
     *
     * @param serverlistid3 the value for FreeHost_IDCProductlist.ServerlistID3
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setServerlistid3(Integer serverlistid3) {
        this.serverlistid3 = serverlistid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.ServerlistID4
     *
     * @return the value of FreeHost_IDCProductlist.ServerlistID4
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getServerlistid4() {
        return serverlistid4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.ServerlistID4
     *
     * @param serverlistid4 the value for FreeHost_IDCProductlist.ServerlistID4
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setServerlistid4(Integer serverlistid4) {
        this.serverlistid4 = serverlistid4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.ServerlistID5
     *
     * @return the value of FreeHost_IDCProductlist.ServerlistID5
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getServerlistid5() {
        return serverlistid5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.ServerlistID5
     *
     * @param serverlistid5 the value for FreeHost_IDCProductlist.ServerlistID5
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setServerlistid5(Integer serverlistid5) {
        this.serverlistid5 = serverlistid5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.canmonth
     *
     * @return the value of FreeHost_IDCProductlist.canmonth
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanmonth() {
        return canmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.canmonth
     *
     * @param canmonth the value for FreeHost_IDCProductlist.canmonth
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanmonth(String canmonth) {
        this.canmonth = canmonth == null ? null : canmonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.canhalfyear
     *
     * @return the value of FreeHost_IDCProductlist.canhalfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanhalfyear() {
        return canhalfyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.canhalfyear
     *
     * @param canhalfyear the value for FreeHost_IDCProductlist.canhalfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanhalfyear(String canhalfyear) {
        this.canhalfyear = canhalfyear == null ? null : canhalfyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.agent1
     *
     * @return the value of FreeHost_IDCProductlist.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent1() {
        return agent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.agent1
     *
     * @param agent1 the value for FreeHost_IDCProductlist.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent1(String agent1) {
        this.agent1 = agent1 == null ? null : agent1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.agent2
     *
     * @return the value of FreeHost_IDCProductlist.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent2() {
        return agent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.agent2
     *
     * @param agent2 the value for FreeHost_IDCProductlist.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent2(String agent2) {
        this.agent2 = agent2 == null ? null : agent2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.canbyenduser
     *
     * @return the value of FreeHost_IDCProductlist.canbyenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanbyenduser() {
        return canbyenduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.canbyenduser
     *
     * @param canbyenduser the value for FreeHost_IDCProductlist.canbyenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanbyenduser(String canbyenduser) {
        this.canbyenduser = canbyenduser == null ? null : canbyenduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.canbyagnenduser
     *
     * @return the value of FreeHost_IDCProductlist.canbyagnenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanbyagnenduser() {
        return canbyagnenduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.canbyagnenduser
     *
     * @param canbyagnenduser the value for FreeHost_IDCProductlist.canbyagnenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanbyagnenduser(String canbyagnenduser) {
        this.canbyagnenduser = canbyagnenduser == null ? null : canbyagnenduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.canbyagn
     *
     * @return the value of FreeHost_IDCProductlist.canbyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanbyagn() {
        return canbyagn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.canbyagn
     *
     * @param canbyagn the value for FreeHost_IDCProductlist.canbyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanbyagn(String canbyagn) {
        this.canbyagn = canbyagn == null ? null : canbyagn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.orderbyid
     *
     * @return the value of FreeHost_IDCProductlist.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getOrderbyid() {
        return orderbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.orderbyid
     *
     * @param orderbyid the value for FreeHost_IDCProductlist.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setOrderbyid(Integer orderbyid) {
        this.orderbyid = orderbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.canshowyear
     *
     * @return the value of FreeHost_IDCProductlist.canshowyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanshowyear() {
        return canshowyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.canshowyear
     *
     * @param canshowyear the value for FreeHost_IDCProductlist.canshowyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanshowyear(String canshowyear) {
        this.canshowyear = canshowyear == null ? null : canshowyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.typeid
     *
     * @return the value of FreeHost_IDCProductlist.typeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.typeid
     *
     * @param typeid the value for FreeHost_IDCProductlist.typeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.canseason
     *
     * @return the value of FreeHost_IDCProductlist.canseason
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanseason() {
        return canseason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.canseason
     *
     * @param canseason the value for FreeHost_IDCProductlist.canseason
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanseason(String canseason) {
        this.canseason = canseason == null ? null : canseason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.allowupdate
     *
     * @return the value of FreeHost_IDCProductlist.allowupdate
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAllowupdate() {
        return allowupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.allowupdate
     *
     * @param allowupdate the value for FreeHost_IDCProductlist.allowupdate
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAllowupdate(String allowupdate) {
        this.allowupdate = allowupdate == null ? null : allowupdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.allowupdatetoother
     *
     * @return the value of FreeHost_IDCProductlist.allowupdatetoother
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAllowupdatetoother() {
        return allowupdatetoother;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.allowupdatetoother
     *
     * @param allowupdatetoother the value for FreeHost_IDCProductlist.allowupdatetoother
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAllowupdatetoother(String allowupdatetoother) {
        this.allowupdatetoother = allowupdatetoother == null ? null : allowupdatetoother.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.updatebytypeid
     *
     * @return the value of FreeHost_IDCProductlist.updatebytypeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getUpdatebytypeid() {
        return updatebytypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.updatebytypeid
     *
     * @param updatebytypeid the value for FreeHost_IDCProductlist.updatebytypeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUpdatebytypeid(String updatebytypeid) {
        this.updatebytypeid = updatebytypeid == null ? null : updatebytypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.price0
     *
     * @return the value of FreeHost_IDCProductlist.price0
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getPrice0() {
        return price0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.price0
     *
     * @param price0 the value for FreeHost_IDCProductlist.price0
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPrice0(BigDecimal price0) {
        this.price0 = price0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.price1
     *
     * @return the value of FreeHost_IDCProductlist.price1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getPrice1() {
        return price1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.price1
     *
     * @param price1 the value for FreeHost_IDCProductlist.price1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPrice1(BigDecimal price1) {
        this.price1 = price1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.price2
     *
     * @return the value of FreeHost_IDCProductlist.price2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getPrice2() {
        return price2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.price2
     *
     * @param price2 the value for FreeHost_IDCProductlist.price2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPrice2(BigDecimal price2) {
        this.price2 = price2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.price3
     *
     * @return the value of FreeHost_IDCProductlist.price3
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getPrice3() {
        return price3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.price3
     *
     * @param price3 the value for FreeHost_IDCProductlist.price3
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPrice3(BigDecimal price3) {
        this.price3 = price3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.price4
     *
     * @return the value of FreeHost_IDCProductlist.price4
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getPrice4() {
        return price4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.price4
     *
     * @param price4 the value for FreeHost_IDCProductlist.price4
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPrice4(BigDecimal price4) {
        this.price4 = price4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.price5
     *
     * @return the value of FreeHost_IDCProductlist.price5
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getPrice5() {
        return price5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.price5
     *
     * @param price5 the value for FreeHost_IDCProductlist.price5
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPrice5(BigDecimal price5) {
        this.price5 = price5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.price6
     *
     * @return the value of FreeHost_IDCProductlist.price6
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getPrice6() {
        return price6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.price6
     *
     * @param price6 the value for FreeHost_IDCProductlist.price6
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPrice6(BigDecimal price6) {
        this.price6 = price6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.price7
     *
     * @return the value of FreeHost_IDCProductlist.price7
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getPrice7() {
        return price7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.price7
     *
     * @param price7 the value for FreeHost_IDCProductlist.price7
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPrice7(BigDecimal price7) {
        this.price7 = price7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.price8
     *
     * @return the value of FreeHost_IDCProductlist.price8
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getPrice8() {
        return price8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.price8
     *
     * @param price8 the value for FreeHost_IDCProductlist.price8
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPrice8(BigDecimal price8) {
        this.price8 = price8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.price9
     *
     * @return the value of FreeHost_IDCProductlist.price9
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getPrice9() {
        return price9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.price9
     *
     * @param price9 the value for FreeHost_IDCProductlist.price9
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPrice9(BigDecimal price9) {
        this.price9 = price9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.price10
     *
     * @return the value of FreeHost_IDCProductlist.price10
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getPrice10() {
        return price10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.price10
     *
     * @param price10 the value for FreeHost_IDCProductlist.price10
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPrice10(BigDecimal price10) {
        this.price10 = price10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.PAY_Month
     *
     * @return the value of FreeHost_IDCProductlist.PAY_Month
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPayMonth() {
        return payMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.PAY_Month
     *
     * @param payMonth the value for FreeHost_IDCProductlist.PAY_Month
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPayMonth(String payMonth) {
        this.payMonth = payMonth == null ? null : payMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.PAY_Season
     *
     * @return the value of FreeHost_IDCProductlist.PAY_Season
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPaySeason() {
        return paySeason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.PAY_Season
     *
     * @param paySeason the value for FreeHost_IDCProductlist.PAY_Season
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPaySeason(String paySeason) {
        this.paySeason = paySeason == null ? null : paySeason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.PAY_halfyear
     *
     * @return the value of FreeHost_IDCProductlist.PAY_halfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPayHalfyear() {
        return payHalfyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.PAY_halfyear
     *
     * @param payHalfyear the value for FreeHost_IDCProductlist.PAY_halfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPayHalfyear(String payHalfyear) {
        this.payHalfyear = payHalfyear == null ? null : payHalfyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.PAY_Nextyear
     *
     * @return the value of FreeHost_IDCProductlist.PAY_Nextyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPayNextyear() {
        return payNextyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.PAY_Nextyear
     *
     * @param payNextyear the value for FreeHost_IDCProductlist.PAY_Nextyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPayNextyear(String payNextyear) {
        this.payNextyear = payNextyear == null ? null : payNextyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.PAY_2year
     *
     * @return the value of FreeHost_IDCProductlist.PAY_2year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPay2year() {
        return pay2year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.PAY_2year
     *
     * @param pay2year the value for FreeHost_IDCProductlist.PAY_2year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPay2year(String pay2year) {
        this.pay2year = pay2year == null ? null : pay2year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.PAY_3year
     *
     * @return the value of FreeHost_IDCProductlist.PAY_3year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPay3year() {
        return pay3year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.PAY_3year
     *
     * @param pay3year the value for FreeHost_IDCProductlist.PAY_3year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPay3year(String pay3year) {
        this.pay3year = pay3year == null ? null : pay3year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.PAY_4year
     *
     * @return the value of FreeHost_IDCProductlist.PAY_4year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPay4year() {
        return pay4year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.PAY_4year
     *
     * @param pay4year the value for FreeHost_IDCProductlist.PAY_4year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPay4year(String pay4year) {
        this.pay4year = pay4year == null ? null : pay4year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.PAY_5year
     *
     * @return the value of FreeHost_IDCProductlist.PAY_5year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPay5year() {
        return pay5year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.PAY_5year
     *
     * @param pay5year the value for FreeHost_IDCProductlist.PAY_5year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPay5year(String pay5year) {
        this.pay5year = pay5year == null ? null : pay5year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist.onlyusebyagn
     *
     * @return the value of FreeHost_IDCProductlist.onlyusebyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getOnlyusebyagn() {
        return onlyusebyagn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist.onlyusebyagn
     *
     * @param onlyusebyagn the value for FreeHost_IDCProductlist.onlyusebyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setOnlyusebyagn(String onlyusebyagn) {
        this.onlyusebyagn = onlyusebyagn == null ? null : onlyusebyagn.trim();
    }
}