package com.ybh.front.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class IDCProductlist_AGNExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public IDCProductlist_AGNExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdctypeIsNull() {
            addCriterion("IDCtype is null");
            return (Criteria) this;
        }

        public Criteria andIdctypeIsNotNull() {
            addCriterion("IDCtype is not null");
            return (Criteria) this;
        }

        public Criteria andIdctypeEqualTo(String value) {
            addCriterion("IDCtype =", value, "idctype");
            return (Criteria) this;
        }

        public Criteria andIdctypeNotEqualTo(String value) {
            addCriterion("IDCtype <>", value, "idctype");
            return (Criteria) this;
        }

        public Criteria andIdctypeGreaterThan(String value) {
            addCriterion("IDCtype >", value, "idctype");
            return (Criteria) this;
        }

        public Criteria andIdctypeGreaterThanOrEqualTo(String value) {
            addCriterion("IDCtype >=", value, "idctype");
            return (Criteria) this;
        }

        public Criteria andIdctypeLessThan(String value) {
            addCriterion("IDCtype <", value, "idctype");
            return (Criteria) this;
        }

        public Criteria andIdctypeLessThanOrEqualTo(String value) {
            addCriterion("IDCtype <=", value, "idctype");
            return (Criteria) this;
        }

        public Criteria andIdctypeLike(String value) {
            addCriterion("IDCtype like", value, "idctype");
            return (Criteria) this;
        }

        public Criteria andIdctypeNotLike(String value) {
            addCriterion("IDCtype not like", value, "idctype");
            return (Criteria) this;
        }

        public Criteria andIdctypeIn(List<String> values) {
            addCriterion("IDCtype in", values, "idctype");
            return (Criteria) this;
        }

        public Criteria andIdctypeNotIn(List<String> values) {
            addCriterion("IDCtype not in", values, "idctype");
            return (Criteria) this;
        }

        public Criteria andIdctypeBetween(String value1, String value2) {
            addCriterion("IDCtype between", value1, value2, "idctype");
            return (Criteria) this;
        }

        public Criteria andIdctypeNotBetween(String value1, String value2) {
            addCriterion("IDCtype not between", value1, value2, "idctype");
            return (Criteria) this;
        }

        public Criteria andIstgIsNull() {
            addCriterion("istg is null");
            return (Criteria) this;
        }

        public Criteria andIstgIsNotNull() {
            addCriterion("istg is not null");
            return (Criteria) this;
        }

        public Criteria andIstgEqualTo(Boolean value) {
            addCriterion("istg =", value, "istg");
            return (Criteria) this;
        }

        public Criteria andIstgNotEqualTo(Boolean value) {
            addCriterion("istg <>", value, "istg");
            return (Criteria) this;
        }

        public Criteria andIstgGreaterThan(Boolean value) {
            addCriterion("istg >", value, "istg");
            return (Criteria) this;
        }

        public Criteria andIstgGreaterThanOrEqualTo(Boolean value) {
            addCriterion("istg >=", value, "istg");
            return (Criteria) this;
        }

        public Criteria andIstgLessThan(Boolean value) {
            addCriterion("istg <", value, "istg");
            return (Criteria) this;
        }

        public Criteria andIstgLessThanOrEqualTo(Boolean value) {
            addCriterion("istg <=", value, "istg");
            return (Criteria) this;
        }

        public Criteria andIstgIn(List<Boolean> values) {
            addCriterion("istg in", values, "istg");
            return (Criteria) this;
        }

        public Criteria andIstgNotIn(List<Boolean> values) {
            addCriterion("istg not in", values, "istg");
            return (Criteria) this;
        }

        public Criteria andIstgBetween(Boolean value1, Boolean value2) {
            addCriterion("istg between", value1, value2, "istg");
            return (Criteria) this;
        }

        public Criteria andIstgNotBetween(Boolean value1, Boolean value2) {
            addCriterion("istg not between", value1, value2, "istg");
            return (Criteria) this;
        }

        public Criteria andUsermoneyIsNull() {
            addCriterion("usermoney is null");
            return (Criteria) this;
        }

        public Criteria andUsermoneyIsNotNull() {
            addCriterion("usermoney is not null");
            return (Criteria) this;
        }

        public Criteria andUsermoneyEqualTo(BigDecimal value) {
            addCriterion("usermoney =", value, "usermoney");
            return (Criteria) this;
        }

        public Criteria andUsermoneyNotEqualTo(BigDecimal value) {
            addCriterion("usermoney <>", value, "usermoney");
            return (Criteria) this;
        }

        public Criteria andUsermoneyGreaterThan(BigDecimal value) {
            addCriterion("usermoney >", value, "usermoney");
            return (Criteria) this;
        }

        public Criteria andUsermoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("usermoney >=", value, "usermoney");
            return (Criteria) this;
        }

        public Criteria andUsermoneyLessThan(BigDecimal value) {
            addCriterion("usermoney <", value, "usermoney");
            return (Criteria) this;
        }

        public Criteria andUsermoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("usermoney <=", value, "usermoney");
            return (Criteria) this;
        }

        public Criteria andUsermoneyIn(List<BigDecimal> values) {
            addCriterion("usermoney in", values, "usermoney");
            return (Criteria) this;
        }

        public Criteria andUsermoneyNotIn(List<BigDecimal> values) {
            addCriterion("usermoney not in", values, "usermoney");
            return (Criteria) this;
        }

        public Criteria andUsermoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("usermoney between", value1, value2, "usermoney");
            return (Criteria) this;
        }

        public Criteria andUsermoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("usermoney not between", value1, value2, "usermoney");
            return (Criteria) this;
        }

        public Criteria andServerlistidIsNull() {
            addCriterion("ServerlistID is null");
            return (Criteria) this;
        }

        public Criteria andServerlistidIsNotNull() {
            addCriterion("ServerlistID is not null");
            return (Criteria) this;
        }

        public Criteria andServerlistidEqualTo(Integer value) {
            addCriterion("ServerlistID =", value, "serverlistid");
            return (Criteria) this;
        }

        public Criteria andServerlistidNotEqualTo(Integer value) {
            addCriterion("ServerlistID <>", value, "serverlistid");
            return (Criteria) this;
        }

        public Criteria andServerlistidGreaterThan(Integer value) {
            addCriterion("ServerlistID >", value, "serverlistid");
            return (Criteria) this;
        }

        public Criteria andServerlistidGreaterThanOrEqualTo(Integer value) {
            addCriterion("ServerlistID >=", value, "serverlistid");
            return (Criteria) this;
        }

        public Criteria andServerlistidLessThan(Integer value) {
            addCriterion("ServerlistID <", value, "serverlistid");
            return (Criteria) this;
        }

        public Criteria andServerlistidLessThanOrEqualTo(Integer value) {
            addCriterion("ServerlistID <=", value, "serverlistid");
            return (Criteria) this;
        }

        public Criteria andServerlistidIn(List<Integer> values) {
            addCriterion("ServerlistID in", values, "serverlistid");
            return (Criteria) this;
        }

        public Criteria andServerlistidNotIn(List<Integer> values) {
            addCriterion("ServerlistID not in", values, "serverlistid");
            return (Criteria) this;
        }

        public Criteria andServerlistidBetween(Integer value1, Integer value2) {
            addCriterion("ServerlistID between", value1, value2, "serverlistid");
            return (Criteria) this;
        }

        public Criteria andServerlistidNotBetween(Integer value1, Integer value2) {
            addCriterion("ServerlistID not between", value1, value2, "serverlistid");
            return (Criteria) this;
        }

        public Criteria andCanmonthIsNull() {
            addCriterion("canmonth is null");
            return (Criteria) this;
        }

        public Criteria andCanmonthIsNotNull() {
            addCriterion("canmonth is not null");
            return (Criteria) this;
        }

        public Criteria andCanmonthEqualTo(String value) {
            addCriterion("canmonth =", value, "canmonth");
            return (Criteria) this;
        }

        public Criteria andCanmonthNotEqualTo(String value) {
            addCriterion("canmonth <>", value, "canmonth");
            return (Criteria) this;
        }

        public Criteria andCanmonthGreaterThan(String value) {
            addCriterion("canmonth >", value, "canmonth");
            return (Criteria) this;
        }

        public Criteria andCanmonthGreaterThanOrEqualTo(String value) {
            addCriterion("canmonth >=", value, "canmonth");
            return (Criteria) this;
        }

        public Criteria andCanmonthLessThan(String value) {
            addCriterion("canmonth <", value, "canmonth");
            return (Criteria) this;
        }

        public Criteria andCanmonthLessThanOrEqualTo(String value) {
            addCriterion("canmonth <=", value, "canmonth");
            return (Criteria) this;
        }

        public Criteria andCanmonthLike(String value) {
            addCriterion("canmonth like", value, "canmonth");
            return (Criteria) this;
        }

        public Criteria andCanmonthNotLike(String value) {
            addCriterion("canmonth not like", value, "canmonth");
            return (Criteria) this;
        }

        public Criteria andCanmonthIn(List<String> values) {
            addCriterion("canmonth in", values, "canmonth");
            return (Criteria) this;
        }

        public Criteria andCanmonthNotIn(List<String> values) {
            addCriterion("canmonth not in", values, "canmonth");
            return (Criteria) this;
        }

        public Criteria andCanmonthBetween(String value1, String value2) {
            addCriterion("canmonth between", value1, value2, "canmonth");
            return (Criteria) this;
        }

        public Criteria andCanmonthNotBetween(String value1, String value2) {
            addCriterion("canmonth not between", value1, value2, "canmonth");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearIsNull() {
            addCriterion("canhalfyear is null");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearIsNotNull() {
            addCriterion("canhalfyear is not null");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearEqualTo(String value) {
            addCriterion("canhalfyear =", value, "canhalfyear");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearNotEqualTo(String value) {
            addCriterion("canhalfyear <>", value, "canhalfyear");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearGreaterThan(String value) {
            addCriterion("canhalfyear >", value, "canhalfyear");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearGreaterThanOrEqualTo(String value) {
            addCriterion("canhalfyear >=", value, "canhalfyear");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearLessThan(String value) {
            addCriterion("canhalfyear <", value, "canhalfyear");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearLessThanOrEqualTo(String value) {
            addCriterion("canhalfyear <=", value, "canhalfyear");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearLike(String value) {
            addCriterion("canhalfyear like", value, "canhalfyear");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearNotLike(String value) {
            addCriterion("canhalfyear not like", value, "canhalfyear");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearIn(List<String> values) {
            addCriterion("canhalfyear in", values, "canhalfyear");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearNotIn(List<String> values) {
            addCriterion("canhalfyear not in", values, "canhalfyear");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearBetween(String value1, String value2) {
            addCriterion("canhalfyear between", value1, value2, "canhalfyear");
            return (Criteria) this;
        }

        public Criteria andCanhalfyearNotBetween(String value1, String value2) {
            addCriterion("canhalfyear not between", value1, value2, "canhalfyear");
            return (Criteria) this;
        }

        public Criteria andAgent1IsNull() {
            addCriterion("agent1 is null");
            return (Criteria) this;
        }

        public Criteria andAgent1IsNotNull() {
            addCriterion("agent1 is not null");
            return (Criteria) this;
        }

        public Criteria andAgent1EqualTo(String value) {
            addCriterion("agent1 =", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1NotEqualTo(String value) {
            addCriterion("agent1 <>", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1GreaterThan(String value) {
            addCriterion("agent1 >", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1GreaterThanOrEqualTo(String value) {
            addCriterion("agent1 >=", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1LessThan(String value) {
            addCriterion("agent1 <", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1LessThanOrEqualTo(String value) {
            addCriterion("agent1 <=", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1Like(String value) {
            addCriterion("agent1 like", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1NotLike(String value) {
            addCriterion("agent1 not like", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1In(List<String> values) {
            addCriterion("agent1 in", values, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1NotIn(List<String> values) {
            addCriterion("agent1 not in", values, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1Between(String value1, String value2) {
            addCriterion("agent1 between", value1, value2, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1NotBetween(String value1, String value2) {
            addCriterion("agent1 not between", value1, value2, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent2IsNull() {
            addCriterion("agent2 is null");
            return (Criteria) this;
        }

        public Criteria andAgent2IsNotNull() {
            addCriterion("agent2 is not null");
            return (Criteria) this;
        }

        public Criteria andAgent2EqualTo(String value) {
            addCriterion("agent2 =", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2NotEqualTo(String value) {
            addCriterion("agent2 <>", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2GreaterThan(String value) {
            addCriterion("agent2 >", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2GreaterThanOrEqualTo(String value) {
            addCriterion("agent2 >=", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2LessThan(String value) {
            addCriterion("agent2 <", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2LessThanOrEqualTo(String value) {
            addCriterion("agent2 <=", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2Like(String value) {
            addCriterion("agent2 like", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2NotLike(String value) {
            addCriterion("agent2 not like", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2In(List<String> values) {
            addCriterion("agent2 in", values, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2NotIn(List<String> values) {
            addCriterion("agent2 not in", values, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2Between(String value1, String value2) {
            addCriterion("agent2 between", value1, value2, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2NotBetween(String value1, String value2) {
            addCriterion("agent2 not between", value1, value2, "agent2");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserIsNull() {
            addCriterion("canbyenduser is null");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserIsNotNull() {
            addCriterion("canbyenduser is not null");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserEqualTo(String value) {
            addCriterion("canbyenduser =", value, "canbyenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserNotEqualTo(String value) {
            addCriterion("canbyenduser <>", value, "canbyenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserGreaterThan(String value) {
            addCriterion("canbyenduser >", value, "canbyenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserGreaterThanOrEqualTo(String value) {
            addCriterion("canbyenduser >=", value, "canbyenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserLessThan(String value) {
            addCriterion("canbyenduser <", value, "canbyenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserLessThanOrEqualTo(String value) {
            addCriterion("canbyenduser <=", value, "canbyenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserLike(String value) {
            addCriterion("canbyenduser like", value, "canbyenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserNotLike(String value) {
            addCriterion("canbyenduser not like", value, "canbyenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserIn(List<String> values) {
            addCriterion("canbyenduser in", values, "canbyenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserNotIn(List<String> values) {
            addCriterion("canbyenduser not in", values, "canbyenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserBetween(String value1, String value2) {
            addCriterion("canbyenduser between", value1, value2, "canbyenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyenduserNotBetween(String value1, String value2) {
            addCriterion("canbyenduser not between", value1, value2, "canbyenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserIsNull() {
            addCriterion("canbyagnenduser is null");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserIsNotNull() {
            addCriterion("canbyagnenduser is not null");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserEqualTo(String value) {
            addCriterion("canbyagnenduser =", value, "canbyagnenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserNotEqualTo(String value) {
            addCriterion("canbyagnenduser <>", value, "canbyagnenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserGreaterThan(String value) {
            addCriterion("canbyagnenduser >", value, "canbyagnenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserGreaterThanOrEqualTo(String value) {
            addCriterion("canbyagnenduser >=", value, "canbyagnenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserLessThan(String value) {
            addCriterion("canbyagnenduser <", value, "canbyagnenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserLessThanOrEqualTo(String value) {
            addCriterion("canbyagnenduser <=", value, "canbyagnenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserLike(String value) {
            addCriterion("canbyagnenduser like", value, "canbyagnenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserNotLike(String value) {
            addCriterion("canbyagnenduser not like", value, "canbyagnenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserIn(List<String> values) {
            addCriterion("canbyagnenduser in", values, "canbyagnenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserNotIn(List<String> values) {
            addCriterion("canbyagnenduser not in", values, "canbyagnenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserBetween(String value1, String value2) {
            addCriterion("canbyagnenduser between", value1, value2, "canbyagnenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyagnenduserNotBetween(String value1, String value2) {
            addCriterion("canbyagnenduser not between", value1, value2, "canbyagnenduser");
            return (Criteria) this;
        }

        public Criteria andCanbyagnIsNull() {
            addCriterion("canbyagn is null");
            return (Criteria) this;
        }

        public Criteria andCanbyagnIsNotNull() {
            addCriterion("canbyagn is not null");
            return (Criteria) this;
        }

        public Criteria andCanbyagnEqualTo(String value) {
            addCriterion("canbyagn =", value, "canbyagn");
            return (Criteria) this;
        }

        public Criteria andCanbyagnNotEqualTo(String value) {
            addCriterion("canbyagn <>", value, "canbyagn");
            return (Criteria) this;
        }

        public Criteria andCanbyagnGreaterThan(String value) {
            addCriterion("canbyagn >", value, "canbyagn");
            return (Criteria) this;
        }

        public Criteria andCanbyagnGreaterThanOrEqualTo(String value) {
            addCriterion("canbyagn >=", value, "canbyagn");
            return (Criteria) this;
        }

        public Criteria andCanbyagnLessThan(String value) {
            addCriterion("canbyagn <", value, "canbyagn");
            return (Criteria) this;
        }

        public Criteria andCanbyagnLessThanOrEqualTo(String value) {
            addCriterion("canbyagn <=", value, "canbyagn");
            return (Criteria) this;
        }

        public Criteria andCanbyagnLike(String value) {
            addCriterion("canbyagn like", value, "canbyagn");
            return (Criteria) this;
        }

        public Criteria andCanbyagnNotLike(String value) {
            addCriterion("canbyagn not like", value, "canbyagn");
            return (Criteria) this;
        }

        public Criteria andCanbyagnIn(List<String> values) {
            addCriterion("canbyagn in", values, "canbyagn");
            return (Criteria) this;
        }

        public Criteria andCanbyagnNotIn(List<String> values) {
            addCriterion("canbyagn not in", values, "canbyagn");
            return (Criteria) this;
        }

        public Criteria andCanbyagnBetween(String value1, String value2) {
            addCriterion("canbyagn between", value1, value2, "canbyagn");
            return (Criteria) this;
        }

        public Criteria andCanbyagnNotBetween(String value1, String value2) {
            addCriterion("canbyagn not between", value1, value2, "canbyagn");
            return (Criteria) this;
        }

        public Criteria andOrderbyidIsNull() {
            addCriterion("orderbyid is null");
            return (Criteria) this;
        }

        public Criteria andOrderbyidIsNotNull() {
            addCriterion("orderbyid is not null");
            return (Criteria) this;
        }

        public Criteria andOrderbyidEqualTo(Integer value) {
            addCriterion("orderbyid =", value, "orderbyid");
            return (Criteria) this;
        }

        public Criteria andOrderbyidNotEqualTo(Integer value) {
            addCriterion("orderbyid <>", value, "orderbyid");
            return (Criteria) this;
        }

        public Criteria andOrderbyidGreaterThan(Integer value) {
            addCriterion("orderbyid >", value, "orderbyid");
            return (Criteria) this;
        }

        public Criteria andOrderbyidGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderbyid >=", value, "orderbyid");
            return (Criteria) this;
        }

        public Criteria andOrderbyidLessThan(Integer value) {
            addCriterion("orderbyid <", value, "orderbyid");
            return (Criteria) this;
        }

        public Criteria andOrderbyidLessThanOrEqualTo(Integer value) {
            addCriterion("orderbyid <=", value, "orderbyid");
            return (Criteria) this;
        }

        public Criteria andOrderbyidIn(List<Integer> values) {
            addCriterion("orderbyid in", values, "orderbyid");
            return (Criteria) this;
        }

        public Criteria andOrderbyidNotIn(List<Integer> values) {
            addCriterion("orderbyid not in", values, "orderbyid");
            return (Criteria) this;
        }

        public Criteria andOrderbyidBetween(Integer value1, Integer value2) {
            addCriterion("orderbyid between", value1, value2, "orderbyid");
            return (Criteria) this;
        }

        public Criteria andOrderbyidNotBetween(Integer value1, Integer value2) {
            addCriterion("orderbyid not between", value1, value2, "orderbyid");
            return (Criteria) this;
        }

        public Criteria andCanshowyearIsNull() {
            addCriterion("canshowyear is null");
            return (Criteria) this;
        }

        public Criteria andCanshowyearIsNotNull() {
            addCriterion("canshowyear is not null");
            return (Criteria) this;
        }

        public Criteria andCanshowyearEqualTo(String value) {
            addCriterion("canshowyear =", value, "canshowyear");
            return (Criteria) this;
        }

        public Criteria andCanshowyearNotEqualTo(String value) {
            addCriterion("canshowyear <>", value, "canshowyear");
            return (Criteria) this;
        }

        public Criteria andCanshowyearGreaterThan(String value) {
            addCriterion("canshowyear >", value, "canshowyear");
            return (Criteria) this;
        }

        public Criteria andCanshowyearGreaterThanOrEqualTo(String value) {
            addCriterion("canshowyear >=", value, "canshowyear");
            return (Criteria) this;
        }

        public Criteria andCanshowyearLessThan(String value) {
            addCriterion("canshowyear <", value, "canshowyear");
            return (Criteria) this;
        }

        public Criteria andCanshowyearLessThanOrEqualTo(String value) {
            addCriterion("canshowyear <=", value, "canshowyear");
            return (Criteria) this;
        }

        public Criteria andCanshowyearLike(String value) {
            addCriterion("canshowyear like", value, "canshowyear");
            return (Criteria) this;
        }

        public Criteria andCanshowyearNotLike(String value) {
            addCriterion("canshowyear not like", value, "canshowyear");
            return (Criteria) this;
        }

        public Criteria andCanshowyearIn(List<String> values) {
            addCriterion("canshowyear in", values, "canshowyear");
            return (Criteria) this;
        }

        public Criteria andCanshowyearNotIn(List<String> values) {
            addCriterion("canshowyear not in", values, "canshowyear");
            return (Criteria) this;
        }

        public Criteria andCanshowyearBetween(String value1, String value2) {
            addCriterion("canshowyear between", value1, value2, "canshowyear");
            return (Criteria) this;
        }

        public Criteria andCanshowyearNotBetween(String value1, String value2) {
            addCriterion("canshowyear not between", value1, value2, "canshowyear");
            return (Criteria) this;
        }

        public Criteria andTypeidIsNull() {
            addCriterion("typeid is null");
            return (Criteria) this;
        }

        public Criteria andTypeidIsNotNull() {
            addCriterion("typeid is not null");
            return (Criteria) this;
        }

        public Criteria andTypeidEqualTo(Integer value) {
            addCriterion("typeid =", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotEqualTo(Integer value) {
            addCriterion("typeid <>", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidGreaterThan(Integer value) {
            addCriterion("typeid >", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("typeid >=", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidLessThan(Integer value) {
            addCriterion("typeid <", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidLessThanOrEqualTo(Integer value) {
            addCriterion("typeid <=", value, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidIn(List<Integer> values) {
            addCriterion("typeid in", values, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotIn(List<Integer> values) {
            addCriterion("typeid not in", values, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidBetween(Integer value1, Integer value2) {
            addCriterion("typeid between", value1, value2, "typeid");
            return (Criteria) this;
        }

        public Criteria andTypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("typeid not between", value1, value2, "typeid");
            return (Criteria) this;
        }

        public Criteria andCanseasonIsNull() {
            addCriterion("canseason is null");
            return (Criteria) this;
        }

        public Criteria andCanseasonIsNotNull() {
            addCriterion("canseason is not null");
            return (Criteria) this;
        }

        public Criteria andCanseasonEqualTo(String value) {
            addCriterion("canseason =", value, "canseason");
            return (Criteria) this;
        }

        public Criteria andCanseasonNotEqualTo(String value) {
            addCriterion("canseason <>", value, "canseason");
            return (Criteria) this;
        }

        public Criteria andCanseasonGreaterThan(String value) {
            addCriterion("canseason >", value, "canseason");
            return (Criteria) this;
        }

        public Criteria andCanseasonGreaterThanOrEqualTo(String value) {
            addCriterion("canseason >=", value, "canseason");
            return (Criteria) this;
        }

        public Criteria andCanseasonLessThan(String value) {
            addCriterion("canseason <", value, "canseason");
            return (Criteria) this;
        }

        public Criteria andCanseasonLessThanOrEqualTo(String value) {
            addCriterion("canseason <=", value, "canseason");
            return (Criteria) this;
        }

        public Criteria andCanseasonLike(String value) {
            addCriterion("canseason like", value, "canseason");
            return (Criteria) this;
        }

        public Criteria andCanseasonNotLike(String value) {
            addCriterion("canseason not like", value, "canseason");
            return (Criteria) this;
        }

        public Criteria andCanseasonIn(List<String> values) {
            addCriterion("canseason in", values, "canseason");
            return (Criteria) this;
        }

        public Criteria andCanseasonNotIn(List<String> values) {
            addCriterion("canseason not in", values, "canseason");
            return (Criteria) this;
        }

        public Criteria andCanseasonBetween(String value1, String value2) {
            addCriterion("canseason between", value1, value2, "canseason");
            return (Criteria) this;
        }

        public Criteria andCanseasonNotBetween(String value1, String value2) {
            addCriterion("canseason not between", value1, value2, "canseason");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidIsNull() {
            addCriterion("updatebytypeid is null");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidIsNotNull() {
            addCriterion("updatebytypeid is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidEqualTo(String value) {
            addCriterion("updatebytypeid =", value, "updatebytypeid");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidNotEqualTo(String value) {
            addCriterion("updatebytypeid <>", value, "updatebytypeid");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidGreaterThan(String value) {
            addCriterion("updatebytypeid >", value, "updatebytypeid");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidGreaterThanOrEqualTo(String value) {
            addCriterion("updatebytypeid >=", value, "updatebytypeid");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidLessThan(String value) {
            addCriterion("updatebytypeid <", value, "updatebytypeid");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidLessThanOrEqualTo(String value) {
            addCriterion("updatebytypeid <=", value, "updatebytypeid");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidLike(String value) {
            addCriterion("updatebytypeid like", value, "updatebytypeid");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidNotLike(String value) {
            addCriterion("updatebytypeid not like", value, "updatebytypeid");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidIn(List<String> values) {
            addCriterion("updatebytypeid in", values, "updatebytypeid");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidNotIn(List<String> values) {
            addCriterion("updatebytypeid not in", values, "updatebytypeid");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidBetween(String value1, String value2) {
            addCriterion("updatebytypeid between", value1, value2, "updatebytypeid");
            return (Criteria) this;
        }

        public Criteria andUpdatebytypeidNotBetween(String value1, String value2) {
            addCriterion("updatebytypeid not between", value1, value2, "updatebytypeid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated do_not_delete_during_merge Fri May 11 11:16:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FreeHost_IDCProductlist_AGN
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}