package com.ybh.front.model;

import java.math.BigDecimal;

public class IDCProductlist_AGN {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.IDCtype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String idctype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.istg
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Boolean istg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.usermoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal usermoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer serverlistid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.canmonth
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canmonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.canhalfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canhalfyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.canbyenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canbyenduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.canbyagnenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canbyagnenduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.canbyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canbyagn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer orderbyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.canshowyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canshowyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.typeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.canseason
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canseason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_IDCProductlist_AGN.updatebytypeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String updatebytypeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.id
     *
     * @return the value of FreeHost_IDCProductlist_AGN.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.id
     *
     * @param id the value for FreeHost_IDCProductlist_AGN.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.IDCtype
     *
     * @return the value of FreeHost_IDCProductlist_AGN.IDCtype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getIdctype() {
        return idctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.IDCtype
     *
     * @param idctype the value for FreeHost_IDCProductlist_AGN.IDCtype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setIdctype(String idctype) {
        this.idctype = idctype == null ? null : idctype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.istg
     *
     * @return the value of FreeHost_IDCProductlist_AGN.istg
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Boolean getIstg() {
        return istg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.istg
     *
     * @param istg the value for FreeHost_IDCProductlist_AGN.istg
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setIstg(Boolean istg) {
        this.istg = istg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.usermoney
     *
     * @return the value of FreeHost_IDCProductlist_AGN.usermoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getUsermoney() {
        return usermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.usermoney
     *
     * @param usermoney the value for FreeHost_IDCProductlist_AGN.usermoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUsermoney(BigDecimal usermoney) {
        this.usermoney = usermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.ServerlistID
     *
     * @return the value of FreeHost_IDCProductlist_AGN.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getServerlistid() {
        return serverlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.ServerlistID
     *
     * @param serverlistid the value for FreeHost_IDCProductlist_AGN.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setServerlistid(Integer serverlistid) {
        this.serverlistid = serverlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.canmonth
     *
     * @return the value of FreeHost_IDCProductlist_AGN.canmonth
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanmonth() {
        return canmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.canmonth
     *
     * @param canmonth the value for FreeHost_IDCProductlist_AGN.canmonth
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanmonth(String canmonth) {
        this.canmonth = canmonth == null ? null : canmonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.canhalfyear
     *
     * @return the value of FreeHost_IDCProductlist_AGN.canhalfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanhalfyear() {
        return canhalfyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.canhalfyear
     *
     * @param canhalfyear the value for FreeHost_IDCProductlist_AGN.canhalfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanhalfyear(String canhalfyear) {
        this.canhalfyear = canhalfyear == null ? null : canhalfyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.agent1
     *
     * @return the value of FreeHost_IDCProductlist_AGN.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent1() {
        return agent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.agent1
     *
     * @param agent1 the value for FreeHost_IDCProductlist_AGN.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent1(String agent1) {
        this.agent1 = agent1 == null ? null : agent1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.agent2
     *
     * @return the value of FreeHost_IDCProductlist_AGN.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent2() {
        return agent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.agent2
     *
     * @param agent2 the value for FreeHost_IDCProductlist_AGN.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent2(String agent2) {
        this.agent2 = agent2 == null ? null : agent2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.canbyenduser
     *
     * @return the value of FreeHost_IDCProductlist_AGN.canbyenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanbyenduser() {
        return canbyenduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.canbyenduser
     *
     * @param canbyenduser the value for FreeHost_IDCProductlist_AGN.canbyenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanbyenduser(String canbyenduser) {
        this.canbyenduser = canbyenduser == null ? null : canbyenduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.canbyagnenduser
     *
     * @return the value of FreeHost_IDCProductlist_AGN.canbyagnenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanbyagnenduser() {
        return canbyagnenduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.canbyagnenduser
     *
     * @param canbyagnenduser the value for FreeHost_IDCProductlist_AGN.canbyagnenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanbyagnenduser(String canbyagnenduser) {
        this.canbyagnenduser = canbyagnenduser == null ? null : canbyagnenduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.canbyagn
     *
     * @return the value of FreeHost_IDCProductlist_AGN.canbyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanbyagn() {
        return canbyagn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.canbyagn
     *
     * @param canbyagn the value for FreeHost_IDCProductlist_AGN.canbyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanbyagn(String canbyagn) {
        this.canbyagn = canbyagn == null ? null : canbyagn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.orderbyid
     *
     * @return the value of FreeHost_IDCProductlist_AGN.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getOrderbyid() {
        return orderbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.orderbyid
     *
     * @param orderbyid the value for FreeHost_IDCProductlist_AGN.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setOrderbyid(Integer orderbyid) {
        this.orderbyid = orderbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.canshowyear
     *
     * @return the value of FreeHost_IDCProductlist_AGN.canshowyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanshowyear() {
        return canshowyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.canshowyear
     *
     * @param canshowyear the value for FreeHost_IDCProductlist_AGN.canshowyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanshowyear(String canshowyear) {
        this.canshowyear = canshowyear == null ? null : canshowyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.typeid
     *
     * @return the value of FreeHost_IDCProductlist_AGN.typeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.typeid
     *
     * @param typeid the value for FreeHost_IDCProductlist_AGN.typeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.canseason
     *
     * @return the value of FreeHost_IDCProductlist_AGN.canseason
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanseason() {
        return canseason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.canseason
     *
     * @param canseason the value for FreeHost_IDCProductlist_AGN.canseason
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanseason(String canseason) {
        this.canseason = canseason == null ? null : canseason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_IDCProductlist_AGN.updatebytypeid
     *
     * @return the value of FreeHost_IDCProductlist_AGN.updatebytypeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getUpdatebytypeid() {
        return updatebytypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_IDCProductlist_AGN.updatebytypeid
     *
     * @param updatebytypeid the value for FreeHost_IDCProductlist_AGN.updatebytypeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUpdatebytypeid(String updatebytypeid) {
        this.updatebytypeid = updatebytypeid == null ? null : updatebytypeid.trim();
    }
}