package com.ybh.front.model;

public class OtherProductlist_AGNWithBLOBs extends OtherProductlist_AGN {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_OtherProductlist_AGN.info
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_OtherProductlist_AGN.infomore
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String infomore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_OtherProductlist_AGN.remindinfo
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String remindinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_OtherProductlist_AGN.info
     *
     * @return the value of FreeHost_OtherProductlist_AGN.info
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_OtherProductlist_AGN.info
     *
     * @param info the value for FreeHost_OtherProductlist_AGN.info
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_OtherProductlist_AGN.infomore
     *
     * @return the value of FreeHost_OtherProductlist_AGN.infomore
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getInfomore() {
        return infomore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_OtherProductlist_AGN.infomore
     *
     * @param infomore the value for FreeHost_OtherProductlist_AGN.infomore
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setInfomore(String infomore) {
        this.infomore = infomore == null ? null : infomore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_OtherProductlist_AGN.remindinfo
     *
     * @return the value of FreeHost_OtherProductlist_AGN.remindinfo
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getRemindinfo() {
        return remindinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_OtherProductlist_AGN.remindinfo
     *
     * @param remindinfo the value for FreeHost_OtherProductlist_AGN.remindinfo
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setRemindinfo(String remindinfo) {
        this.remindinfo = remindinfo == null ? null : remindinfo.trim();
    }
}