package com.ybh.front.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Preopen_ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Preopen_ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andHavegetIsNull() {
            addCriterion("haveget is null");
            return (Criteria) this;
        }

        public Criteria andHavegetIsNotNull() {
            addCriterion("haveget is not null");
            return (Criteria) this;
        }

        public Criteria andHavegetEqualTo(String value) {
            addCriterion("haveget =", value, "haveget");
            return (Criteria) this;
        }

        public Criteria andHavegetNotEqualTo(String value) {
            addCriterion("haveget <>", value, "haveget");
            return (Criteria) this;
        }

        public Criteria andHavegetGreaterThan(String value) {
            addCriterion("haveget >", value, "haveget");
            return (Criteria) this;
        }

        public Criteria andHavegetGreaterThanOrEqualTo(String value) {
            addCriterion("haveget >=", value, "haveget");
            return (Criteria) this;
        }

        public Criteria andHavegetLessThan(String value) {
            addCriterion("haveget <", value, "haveget");
            return (Criteria) this;
        }

        public Criteria andHavegetLessThanOrEqualTo(String value) {
            addCriterion("haveget <=", value, "haveget");
            return (Criteria) this;
        }

        public Criteria andHavegetLike(String value) {
            addCriterion("haveget like", value, "haveget");
            return (Criteria) this;
        }

        public Criteria andHavegetNotLike(String value) {
            addCriterion("haveget not like", value, "haveget");
            return (Criteria) this;
        }

        public Criteria andHavegetIn(List<String> values) {
            addCriterion("haveget in", values, "haveget");
            return (Criteria) this;
        }

        public Criteria andHavegetNotIn(List<String> values) {
            addCriterion("haveget not in", values, "haveget");
            return (Criteria) this;
        }

        public Criteria andHavegetBetween(String value1, String value2) {
            addCriterion("haveget between", value1, value2, "haveget");
            return (Criteria) this;
        }

        public Criteria andHavegetNotBetween(String value1, String value2) {
            addCriterion("haveget not between", value1, value2, "haveget");
            return (Criteria) this;
        }

        public Criteria andByidIsNull() {
            addCriterion("byid is null");
            return (Criteria) this;
        }

        public Criteria andByidIsNotNull() {
            addCriterion("byid is not null");
            return (Criteria) this;
        }

        public Criteria andByidEqualTo(Integer value) {
            addCriterion("byid =", value, "byid");
            return (Criteria) this;
        }

        public Criteria andByidNotEqualTo(Integer value) {
            addCriterion("byid <>", value, "byid");
            return (Criteria) this;
        }

        public Criteria andByidGreaterThan(Integer value) {
            addCriterion("byid >", value, "byid");
            return (Criteria) this;
        }

        public Criteria andByidGreaterThanOrEqualTo(Integer value) {
            addCriterion("byid >=", value, "byid");
            return (Criteria) this;
        }

        public Criteria andByidLessThan(Integer value) {
            addCriterion("byid <", value, "byid");
            return (Criteria) this;
        }

        public Criteria andByidLessThanOrEqualTo(Integer value) {
            addCriterion("byid <=", value, "byid");
            return (Criteria) this;
        }

        public Criteria andByidIn(List<Integer> values) {
            addCriterion("byid in", values, "byid");
            return (Criteria) this;
        }

        public Criteria andByidNotIn(List<Integer> values) {
            addCriterion("byid not in", values, "byid");
            return (Criteria) this;
        }

        public Criteria andByidBetween(Integer value1, Integer value2) {
            addCriterion("byid between", value1, value2, "byid");
            return (Criteria) this;
        }

        public Criteria andByidNotBetween(Integer value1, Integer value2) {
            addCriterion("byid not between", value1, value2, "byid");
            return (Criteria) this;
        }

        public Criteria andWhichproductIsNull() {
            addCriterion("whichProduct is null");
            return (Criteria) this;
        }

        public Criteria andWhichproductIsNotNull() {
            addCriterion("whichProduct is not null");
            return (Criteria) this;
        }

        public Criteria andWhichproductEqualTo(String value) {
            addCriterion("whichProduct =", value, "whichproduct");
            return (Criteria) this;
        }

        public Criteria andWhichproductNotEqualTo(String value) {
            addCriterion("whichProduct <>", value, "whichproduct");
            return (Criteria) this;
        }

        public Criteria andWhichproductGreaterThan(String value) {
            addCriterion("whichProduct >", value, "whichproduct");
            return (Criteria) this;
        }

        public Criteria andWhichproductGreaterThanOrEqualTo(String value) {
            addCriterion("whichProduct >=", value, "whichproduct");
            return (Criteria) this;
        }

        public Criteria andWhichproductLessThan(String value) {
            addCriterion("whichProduct <", value, "whichproduct");
            return (Criteria) this;
        }

        public Criteria andWhichproductLessThanOrEqualTo(String value) {
            addCriterion("whichProduct <=", value, "whichproduct");
            return (Criteria) this;
        }

        public Criteria andWhichproductLike(String value) {
            addCriterion("whichProduct like", value, "whichproduct");
            return (Criteria) this;
        }

        public Criteria andWhichproductNotLike(String value) {
            addCriterion("whichProduct not like", value, "whichproduct");
            return (Criteria) this;
        }

        public Criteria andWhichproductIn(List<String> values) {
            addCriterion("whichProduct in", values, "whichproduct");
            return (Criteria) this;
        }

        public Criteria andWhichproductNotIn(List<String> values) {
            addCriterion("whichProduct not in", values, "whichproduct");
            return (Criteria) this;
        }

        public Criteria andWhichproductBetween(String value1, String value2) {
            addCriterion("whichProduct between", value1, value2, "whichproduct");
            return (Criteria) this;
        }

        public Criteria andWhichproductNotBetween(String value1, String value2) {
            addCriterion("whichProduct not between", value1, value2, "whichproduct");
            return (Criteria) this;
        }

        public Criteria andType1IsNull() {
            addCriterion("type1 is null");
            return (Criteria) this;
        }

        public Criteria andType1IsNotNull() {
            addCriterion("type1 is not null");
            return (Criteria) this;
        }

        public Criteria andType1EqualTo(String value) {
            addCriterion("type1 =", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotEqualTo(String value) {
            addCriterion("type1 <>", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1GreaterThan(String value) {
            addCriterion("type1 >", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1GreaterThanOrEqualTo(String value) {
            addCriterion("type1 >=", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1LessThan(String value) {
            addCriterion("type1 <", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1LessThanOrEqualTo(String value) {
            addCriterion("type1 <=", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1Like(String value) {
            addCriterion("type1 like", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotLike(String value) {
            addCriterion("type1 not like", value, "type1");
            return (Criteria) this;
        }

        public Criteria andType1In(List<String> values) {
            addCriterion("type1 in", values, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotIn(List<String> values) {
            addCriterion("type1 not in", values, "type1");
            return (Criteria) this;
        }

        public Criteria andType1Between(String value1, String value2) {
            addCriterion("type1 between", value1, value2, "type1");
            return (Criteria) this;
        }

        public Criteria andType1NotBetween(String value1, String value2) {
            addCriterion("type1 not between", value1, value2, "type1");
            return (Criteria) this;
        }

        public Criteria andAttimeIsNull() {
            addCriterion("attime is null");
            return (Criteria) this;
        }

        public Criteria andAttimeIsNotNull() {
            addCriterion("attime is not null");
            return (Criteria) this;
        }

        public Criteria andAttimeEqualTo(Date value) {
            addCriterion("attime =", value, "attime");
            return (Criteria) this;
        }

        public Criteria andAttimeNotEqualTo(Date value) {
            addCriterion("attime <>", value, "attime");
            return (Criteria) this;
        }

        public Criteria andAttimeGreaterThan(Date value) {
            addCriterion("attime >", value, "attime");
            return (Criteria) this;
        }

        public Criteria andAttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("attime >=", value, "attime");
            return (Criteria) this;
        }

        public Criteria andAttimeLessThan(Date value) {
            addCriterion("attime <", value, "attime");
            return (Criteria) this;
        }

        public Criteria andAttimeLessThanOrEqualTo(Date value) {
            addCriterion("attime <=", value, "attime");
            return (Criteria) this;
        }

        public Criteria andAttimeIn(List<Date> values) {
            addCriterion("attime in", values, "attime");
            return (Criteria) this;
        }

        public Criteria andAttimeNotIn(List<Date> values) {
            addCriterion("attime not in", values, "attime");
            return (Criteria) this;
        }

        public Criteria andAttimeBetween(Date value1, Date value2) {
            addCriterion("attime between", value1, value2, "attime");
            return (Criteria) this;
        }

        public Criteria andAttimeNotBetween(Date value1, Date value2) {
            addCriterion("attime not between", value1, value2, "attime");
            return (Criteria) this;
        }

        public Criteria andAgent1IsNull() {
            addCriterion("agent1 is null");
            return (Criteria) this;
        }

        public Criteria andAgent1IsNotNull() {
            addCriterion("agent1 is not null");
            return (Criteria) this;
        }

        public Criteria andAgent1EqualTo(String value) {
            addCriterion("agent1 =", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1NotEqualTo(String value) {
            addCriterion("agent1 <>", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1GreaterThan(String value) {
            addCriterion("agent1 >", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1GreaterThanOrEqualTo(String value) {
            addCriterion("agent1 >=", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1LessThan(String value) {
            addCriterion("agent1 <", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1LessThanOrEqualTo(String value) {
            addCriterion("agent1 <=", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1Like(String value) {
            addCriterion("agent1 like", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1NotLike(String value) {
            addCriterion("agent1 not like", value, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1In(List<String> values) {
            addCriterion("agent1 in", values, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1NotIn(List<String> values) {
            addCriterion("agent1 not in", values, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1Between(String value1, String value2) {
            addCriterion("agent1 between", value1, value2, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent1NotBetween(String value1, String value2) {
            addCriterion("agent1 not between", value1, value2, "agent1");
            return (Criteria) this;
        }

        public Criteria andAgent2IsNull() {
            addCriterion("agent2 is null");
            return (Criteria) this;
        }

        public Criteria andAgent2IsNotNull() {
            addCriterion("agent2 is not null");
            return (Criteria) this;
        }

        public Criteria andAgent2EqualTo(String value) {
            addCriterion("agent2 =", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2NotEqualTo(String value) {
            addCriterion("agent2 <>", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2GreaterThan(String value) {
            addCriterion("agent2 >", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2GreaterThanOrEqualTo(String value) {
            addCriterion("agent2 >=", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2LessThan(String value) {
            addCriterion("agent2 <", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2LessThanOrEqualTo(String value) {
            addCriterion("agent2 <=", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2Like(String value) {
            addCriterion("agent2 like", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2NotLike(String value) {
            addCriterion("agent2 not like", value, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2In(List<String> values) {
            addCriterion("agent2 in", values, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2NotIn(List<String> values) {
            addCriterion("agent2 not in", values, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2Between(String value1, String value2) {
            addCriterion("agent2 between", value1, value2, "agent2");
            return (Criteria) this;
        }

        public Criteria andAgent2NotBetween(String value1, String value2) {
            addCriterion("agent2 not between", value1, value2, "agent2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated do_not_delete_during_merge Fri May 11 11:16:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FreeHost_Preopen_Product
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}