package com.ybh.front.model;

import java.math.BigDecimal;
import java.util.Date;

public class Product_Other {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.username
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer serverlistid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.Othertype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String othertype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.starttime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.endtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.istest
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String istest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.status
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.Othercount
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer othercount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.userspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer userspacelimt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.domainspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer domainspacelimt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.domainmustsame
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String domainmustsame;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.Otherstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String otherstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.byhost
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer byhost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer orderbyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.emailstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String emailstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.ordertime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date ordertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.finishtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date finishtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.repaymoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal repaymoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.kefu
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String kefu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.realmoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal realmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Other.smsstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String smsstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.id
     *
     * @return the value of FreeHost_Product_Other.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.id
     *
     * @param id the value for FreeHost_Product_Other.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.username
     *
     * @return the value of FreeHost_Product_Other.username
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.username
     *
     * @param username the value for FreeHost_Product_Other.username
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.ServerlistID
     *
     * @return the value of FreeHost_Product_Other.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getServerlistid() {
        return serverlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.ServerlistID
     *
     * @param serverlistid the value for FreeHost_Product_Other.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setServerlistid(Integer serverlistid) {
        this.serverlistid = serverlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.Othertype
     *
     * @return the value of FreeHost_Product_Other.Othertype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getOthertype() {
        return othertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.Othertype
     *
     * @param othertype the value for FreeHost_Product_Other.Othertype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setOthertype(String othertype) {
        this.othertype = othertype == null ? null : othertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.starttime
     *
     * @return the value of FreeHost_Product_Other.starttime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.starttime
     *
     * @param starttime the value for FreeHost_Product_Other.starttime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.endtime
     *
     * @return the value of FreeHost_Product_Other.endtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.endtime
     *
     * @param endtime the value for FreeHost_Product_Other.endtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.istest
     *
     * @return the value of FreeHost_Product_Other.istest
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getIstest() {
        return istest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.istest
     *
     * @param istest the value for FreeHost_Product_Other.istest
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setIstest(String istest) {
        this.istest = istest == null ? null : istest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.status
     *
     * @return the value of FreeHost_Product_Other.status
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.status
     *
     * @param status the value for FreeHost_Product_Other.status
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.Othercount
     *
     * @return the value of FreeHost_Product_Other.Othercount
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getOthercount() {
        return othercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.Othercount
     *
     * @param othercount the value for FreeHost_Product_Other.Othercount
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setOthercount(Integer othercount) {
        this.othercount = othercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.userspacelimt
     *
     * @return the value of FreeHost_Product_Other.userspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getUserspacelimt() {
        return userspacelimt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.userspacelimt
     *
     * @param userspacelimt the value for FreeHost_Product_Other.userspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUserspacelimt(Integer userspacelimt) {
        this.userspacelimt = userspacelimt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.domainspacelimt
     *
     * @return the value of FreeHost_Product_Other.domainspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getDomainspacelimt() {
        return domainspacelimt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.domainspacelimt
     *
     * @param domainspacelimt the value for FreeHost_Product_Other.domainspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setDomainspacelimt(Integer domainspacelimt) {
        this.domainspacelimt = domainspacelimt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.domainmustsame
     *
     * @return the value of FreeHost_Product_Other.domainmustsame
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getDomainmustsame() {
        return domainmustsame;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.domainmustsame
     *
     * @param domainmustsame the value for FreeHost_Product_Other.domainmustsame
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setDomainmustsame(String domainmustsame) {
        this.domainmustsame = domainmustsame == null ? null : domainmustsame.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.Otherstatus
     *
     * @return the value of FreeHost_Product_Other.Otherstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getOtherstatus() {
        return otherstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.Otherstatus
     *
     * @param otherstatus the value for FreeHost_Product_Other.Otherstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setOtherstatus(String otherstatus) {
        this.otherstatus = otherstatus == null ? null : otherstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.agent1
     *
     * @return the value of FreeHost_Product_Other.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent1() {
        return agent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.agent1
     *
     * @param agent1 the value for FreeHost_Product_Other.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent1(String agent1) {
        this.agent1 = agent1 == null ? null : agent1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.agent2
     *
     * @return the value of FreeHost_Product_Other.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent2() {
        return agent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.agent2
     *
     * @param agent2 the value for FreeHost_Product_Other.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent2(String agent2) {
        this.agent2 = agent2 == null ? null : agent2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.byhost
     *
     * @return the value of FreeHost_Product_Other.byhost
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getByhost() {
        return byhost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.byhost
     *
     * @param byhost the value for FreeHost_Product_Other.byhost
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setByhost(Integer byhost) {
        this.byhost = byhost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.orderbyid
     *
     * @return the value of FreeHost_Product_Other.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getOrderbyid() {
        return orderbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.orderbyid
     *
     * @param orderbyid the value for FreeHost_Product_Other.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setOrderbyid(Integer orderbyid) {
        this.orderbyid = orderbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.emailstatus
     *
     * @return the value of FreeHost_Product_Other.emailstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getEmailstatus() {
        return emailstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.emailstatus
     *
     * @param emailstatus the value for FreeHost_Product_Other.emailstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setEmailstatus(String emailstatus) {
        this.emailstatus = emailstatus == null ? null : emailstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.ordertime
     *
     * @return the value of FreeHost_Product_Other.ordertime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getOrdertime() {
        return ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.ordertime
     *
     * @param ordertime the value for FreeHost_Product_Other.ordertime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setOrdertime(Date ordertime) {
        this.ordertime = ordertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.finishtime
     *
     * @return the value of FreeHost_Product_Other.finishtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getFinishtime() {
        return finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.finishtime
     *
     * @param finishtime the value for FreeHost_Product_Other.finishtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setFinishtime(Date finishtime) {
        this.finishtime = finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.repaymoney
     *
     * @return the value of FreeHost_Product_Other.repaymoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getRepaymoney() {
        return repaymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.repaymoney
     *
     * @param repaymoney the value for FreeHost_Product_Other.repaymoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setRepaymoney(BigDecimal repaymoney) {
        this.repaymoney = repaymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.kefu
     *
     * @return the value of FreeHost_Product_Other.kefu
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getKefu() {
        return kefu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.kefu
     *
     * @param kefu the value for FreeHost_Product_Other.kefu
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setKefu(String kefu) {
        this.kefu = kefu == null ? null : kefu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.realmoney
     *
     * @return the value of FreeHost_Product_Other.realmoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getRealmoney() {
        return realmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.realmoney
     *
     * @param realmoney the value for FreeHost_Product_Other.realmoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setRealmoney(BigDecimal realmoney) {
        this.realmoney = realmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Other.smsstatus
     *
     * @return the value of FreeHost_Product_Other.smsstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getSmsstatus() {
        return smsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Other.smsstatus
     *
     * @param smsstatus the value for FreeHost_Product_Other.smsstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setSmsstatus(String smsstatus) {
        this.smsstatus = smsstatus == null ? null : smsstatus.trim();
    }
}