package com.ybh.front.model;

import java.math.BigDecimal;
import java.util.Date;

public class Product_Sql {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.username
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer serverlistid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.Sqltype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String sqltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.starttime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.endtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.istest
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String istest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.canmonth
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canmonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.canhalfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canhalfyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.status
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.Sqlcount
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer sqlcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.userspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer userspacelimt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.logspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer logspacelimt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.backuptype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer backuptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.lastbackup
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date lastbackup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.Sqlstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String sqlstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.sqlname
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String sqlname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.sqlpassword
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String sqlpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.emailstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String emailstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer orderbyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.byhost
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer byhost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.backuptime1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date backuptime1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.backuptime2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date backuptime2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.backuptime3
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date backuptime3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.backuptime4
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date backuptime4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.backuptime5
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date backuptime5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.randir
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String randir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.ftpname
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String ftpname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.ftppassword
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String ftppassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.ftpendtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date ftpendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.ip1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String ip1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.ip2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String ip2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.userspacelimtReal
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer userspacelimtreal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.logspacelimtReal
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer logspacelimtreal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.checktime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Date checktime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.repaymoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal repaymoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.kefu
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String kefu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.realmoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal realmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_Product_Sql.smsstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String smsstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.id
     *
     * @return the value of FreeHost_Product_Sql.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.id
     *
     * @param id the value for FreeHost_Product_Sql.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.username
     *
     * @return the value of FreeHost_Product_Sql.username
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.username
     *
     * @param username the value for FreeHost_Product_Sql.username
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.ServerlistID
     *
     * @return the value of FreeHost_Product_Sql.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getServerlistid() {
        return serverlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.ServerlistID
     *
     * @param serverlistid the value for FreeHost_Product_Sql.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setServerlistid(Integer serverlistid) {
        this.serverlistid = serverlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.Sqltype
     *
     * @return the value of FreeHost_Product_Sql.Sqltype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getSqltype() {
        return sqltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.Sqltype
     *
     * @param sqltype the value for FreeHost_Product_Sql.Sqltype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setSqltype(String sqltype) {
        this.sqltype = sqltype == null ? null : sqltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.starttime
     *
     * @return the value of FreeHost_Product_Sql.starttime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.starttime
     *
     * @param starttime the value for FreeHost_Product_Sql.starttime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.endtime
     *
     * @return the value of FreeHost_Product_Sql.endtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.endtime
     *
     * @param endtime the value for FreeHost_Product_Sql.endtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.istest
     *
     * @return the value of FreeHost_Product_Sql.istest
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getIstest() {
        return istest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.istest
     *
     * @param istest the value for FreeHost_Product_Sql.istest
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setIstest(String istest) {
        this.istest = istest == null ? null : istest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.canmonth
     *
     * @return the value of FreeHost_Product_Sql.canmonth
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanmonth() {
        return canmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.canmonth
     *
     * @param canmonth the value for FreeHost_Product_Sql.canmonth
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanmonth(String canmonth) {
        this.canmonth = canmonth == null ? null : canmonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.canhalfyear
     *
     * @return the value of FreeHost_Product_Sql.canhalfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanhalfyear() {
        return canhalfyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.canhalfyear
     *
     * @param canhalfyear the value for FreeHost_Product_Sql.canhalfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanhalfyear(String canhalfyear) {
        this.canhalfyear = canhalfyear == null ? null : canhalfyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.status
     *
     * @return the value of FreeHost_Product_Sql.status
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.status
     *
     * @param status the value for FreeHost_Product_Sql.status
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.Sqlcount
     *
     * @return the value of FreeHost_Product_Sql.Sqlcount
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getSqlcount() {
        return sqlcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.Sqlcount
     *
     * @param sqlcount the value for FreeHost_Product_Sql.Sqlcount
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setSqlcount(Integer sqlcount) {
        this.sqlcount = sqlcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.userspacelimt
     *
     * @return the value of FreeHost_Product_Sql.userspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getUserspacelimt() {
        return userspacelimt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.userspacelimt
     *
     * @param userspacelimt the value for FreeHost_Product_Sql.userspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUserspacelimt(Integer userspacelimt) {
        this.userspacelimt = userspacelimt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.logspacelimt
     *
     * @return the value of FreeHost_Product_Sql.logspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getLogspacelimt() {
        return logspacelimt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.logspacelimt
     *
     * @param logspacelimt the value for FreeHost_Product_Sql.logspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setLogspacelimt(Integer logspacelimt) {
        this.logspacelimt = logspacelimt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.backuptype
     *
     * @return the value of FreeHost_Product_Sql.backuptype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getBackuptype() {
        return backuptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.backuptype
     *
     * @param backuptype the value for FreeHost_Product_Sql.backuptype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setBackuptype(Integer backuptype) {
        this.backuptype = backuptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.lastbackup
     *
     * @return the value of FreeHost_Product_Sql.lastbackup
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getLastbackup() {
        return lastbackup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.lastbackup
     *
     * @param lastbackup the value for FreeHost_Product_Sql.lastbackup
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setLastbackup(Date lastbackup) {
        this.lastbackup = lastbackup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.Sqlstatus
     *
     * @return the value of FreeHost_Product_Sql.Sqlstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getSqlstatus() {
        return sqlstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.Sqlstatus
     *
     * @param sqlstatus the value for FreeHost_Product_Sql.Sqlstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setSqlstatus(String sqlstatus) {
        this.sqlstatus = sqlstatus == null ? null : sqlstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.sqlname
     *
     * @return the value of FreeHost_Product_Sql.sqlname
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getSqlname() {
        return sqlname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.sqlname
     *
     * @param sqlname the value for FreeHost_Product_Sql.sqlname
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setSqlname(String sqlname) {
        this.sqlname = sqlname == null ? null : sqlname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.sqlpassword
     *
     * @return the value of FreeHost_Product_Sql.sqlpassword
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getSqlpassword() {
        return sqlpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.sqlpassword
     *
     * @param sqlpassword the value for FreeHost_Product_Sql.sqlpassword
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setSqlpassword(String sqlpassword) {
        this.sqlpassword = sqlpassword == null ? null : sqlpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.emailstatus
     *
     * @return the value of FreeHost_Product_Sql.emailstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getEmailstatus() {
        return emailstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.emailstatus
     *
     * @param emailstatus the value for FreeHost_Product_Sql.emailstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setEmailstatus(String emailstatus) {
        this.emailstatus = emailstatus == null ? null : emailstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.agent1
     *
     * @return the value of FreeHost_Product_Sql.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent1() {
        return agent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.agent1
     *
     * @param agent1 the value for FreeHost_Product_Sql.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent1(String agent1) {
        this.agent1 = agent1 == null ? null : agent1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.agent2
     *
     * @return the value of FreeHost_Product_Sql.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent2() {
        return agent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.agent2
     *
     * @param agent2 the value for FreeHost_Product_Sql.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent2(String agent2) {
        this.agent2 = agent2 == null ? null : agent2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.orderbyid
     *
     * @return the value of FreeHost_Product_Sql.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getOrderbyid() {
        return orderbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.orderbyid
     *
     * @param orderbyid the value for FreeHost_Product_Sql.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setOrderbyid(Integer orderbyid) {
        this.orderbyid = orderbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.byhost
     *
     * @return the value of FreeHost_Product_Sql.byhost
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getByhost() {
        return byhost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.byhost
     *
     * @param byhost the value for FreeHost_Product_Sql.byhost
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setByhost(Integer byhost) {
        this.byhost = byhost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.backuptime1
     *
     * @return the value of FreeHost_Product_Sql.backuptime1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getBackuptime1() {
        return backuptime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.backuptime1
     *
     * @param backuptime1 the value for FreeHost_Product_Sql.backuptime1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setBackuptime1(Date backuptime1) {
        this.backuptime1 = backuptime1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.backuptime2
     *
     * @return the value of FreeHost_Product_Sql.backuptime2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getBackuptime2() {
        return backuptime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.backuptime2
     *
     * @param backuptime2 the value for FreeHost_Product_Sql.backuptime2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setBackuptime2(Date backuptime2) {
        this.backuptime2 = backuptime2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.backuptime3
     *
     * @return the value of FreeHost_Product_Sql.backuptime3
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getBackuptime3() {
        return backuptime3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.backuptime3
     *
     * @param backuptime3 the value for FreeHost_Product_Sql.backuptime3
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setBackuptime3(Date backuptime3) {
        this.backuptime3 = backuptime3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.backuptime4
     *
     * @return the value of FreeHost_Product_Sql.backuptime4
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getBackuptime4() {
        return backuptime4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.backuptime4
     *
     * @param backuptime4 the value for FreeHost_Product_Sql.backuptime4
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setBackuptime4(Date backuptime4) {
        this.backuptime4 = backuptime4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.backuptime5
     *
     * @return the value of FreeHost_Product_Sql.backuptime5
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getBackuptime5() {
        return backuptime5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.backuptime5
     *
     * @param backuptime5 the value for FreeHost_Product_Sql.backuptime5
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setBackuptime5(Date backuptime5) {
        this.backuptime5 = backuptime5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.randir
     *
     * @return the value of FreeHost_Product_Sql.randir
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getRandir() {
        return randir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.randir
     *
     * @param randir the value for FreeHost_Product_Sql.randir
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setRandir(String randir) {
        this.randir = randir == null ? null : randir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.ftpname
     *
     * @return the value of FreeHost_Product_Sql.ftpname
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getFtpname() {
        return ftpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.ftpname
     *
     * @param ftpname the value for FreeHost_Product_Sql.ftpname
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setFtpname(String ftpname) {
        this.ftpname = ftpname == null ? null : ftpname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.ftppassword
     *
     * @return the value of FreeHost_Product_Sql.ftppassword
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getFtppassword() {
        return ftppassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.ftppassword
     *
     * @param ftppassword the value for FreeHost_Product_Sql.ftppassword
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setFtppassword(String ftppassword) {
        this.ftppassword = ftppassword == null ? null : ftppassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.ftpendtime
     *
     * @return the value of FreeHost_Product_Sql.ftpendtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getFtpendtime() {
        return ftpendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.ftpendtime
     *
     * @param ftpendtime the value for FreeHost_Product_Sql.ftpendtime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setFtpendtime(Date ftpendtime) {
        this.ftpendtime = ftpendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.ip1
     *
     * @return the value of FreeHost_Product_Sql.ip1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getIp1() {
        return ip1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.ip1
     *
     * @param ip1 the value for FreeHost_Product_Sql.ip1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setIp1(String ip1) {
        this.ip1 = ip1 == null ? null : ip1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.ip2
     *
     * @return the value of FreeHost_Product_Sql.ip2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getIp2() {
        return ip2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.ip2
     *
     * @param ip2 the value for FreeHost_Product_Sql.ip2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setIp2(String ip2) {
        this.ip2 = ip2 == null ? null : ip2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.userspacelimtReal
     *
     * @return the value of FreeHost_Product_Sql.userspacelimtReal
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getUserspacelimtreal() {
        return userspacelimtreal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.userspacelimtReal
     *
     * @param userspacelimtreal the value for FreeHost_Product_Sql.userspacelimtReal
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUserspacelimtreal(Integer userspacelimtreal) {
        this.userspacelimtreal = userspacelimtreal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.logspacelimtReal
     *
     * @return the value of FreeHost_Product_Sql.logspacelimtReal
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getLogspacelimtreal() {
        return logspacelimtreal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.logspacelimtReal
     *
     * @param logspacelimtreal the value for FreeHost_Product_Sql.logspacelimtReal
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setLogspacelimtreal(Integer logspacelimtreal) {
        this.logspacelimtreal = logspacelimtreal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.checktime
     *
     * @return the value of FreeHost_Product_Sql.checktime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.checktime
     *
     * @param checktime the value for FreeHost_Product_Sql.checktime
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.repaymoney
     *
     * @return the value of FreeHost_Product_Sql.repaymoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getRepaymoney() {
        return repaymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.repaymoney
     *
     * @param repaymoney the value for FreeHost_Product_Sql.repaymoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setRepaymoney(BigDecimal repaymoney) {
        this.repaymoney = repaymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.kefu
     *
     * @return the value of FreeHost_Product_Sql.kefu
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getKefu() {
        return kefu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.kefu
     *
     * @param kefu the value for FreeHost_Product_Sql.kefu
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setKefu(String kefu) {
        this.kefu = kefu == null ? null : kefu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.realmoney
     *
     * @return the value of FreeHost_Product_Sql.realmoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getRealmoney() {
        return realmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.realmoney
     *
     * @param realmoney the value for FreeHost_Product_Sql.realmoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setRealmoney(BigDecimal realmoney) {
        this.realmoney = realmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_Product_Sql.smsstatus
     *
     * @return the value of FreeHost_Product_Sql.smsstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getSmsstatus() {
        return smsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_Product_Sql.smsstatus
     *
     * @param smsstatus the value for FreeHost_Product_Sql.smsstatus
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setSmsstatus(String smsstatus) {
        this.smsstatus = smsstatus == null ? null : smsstatus.trim();
    }
}