package com.ybh.front.model;

import java.math.BigDecimal;

public class SqlProductlist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.Sqltype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String sqltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.Sqlcount
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer sqlcount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.usermoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Double usermoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.userspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer userspacelimt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.logspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer logspacelimt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.backuptype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer backuptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer serverlistid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.isbyhost
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String isbyhost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.Hosttype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String hosttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.cantest
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String cantest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.canmonth
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canmonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.canhalfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canhalfyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String agent2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.canbyenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canbyenduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.canbyagnenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canbyagnenduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.canbyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canbyagn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer orderbyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.ServerlistID2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer serverlistid2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.ServerlistID3
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer serverlistid3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.ServerlistID4
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer serverlistid4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.ServerlistID5
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer serverlistid5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.typeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.canseason
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canseason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.updatebytypeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String updatebytypeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.canupdatespace
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String canupdatespace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.updatespacemoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private BigDecimal updatespacemoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.PAY_Month
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String payMonth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.PAY_Season
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String paySeason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.PAY_halfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String payHalfyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.PAY_Nextyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String payNextyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.PAY_2year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String pay2year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.PAY_3year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String pay3year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.PAY_4year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String pay4year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.PAY_5year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String pay5year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FreeHost_SqlProductlist.onlyusebyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    private String onlyusebyagn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.id
     *
     * @return the value of FreeHost_SqlProductlist.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.id
     *
     * @param id the value for FreeHost_SqlProductlist.id
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.Sqltype
     *
     * @return the value of FreeHost_SqlProductlist.Sqltype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getSqltype() {
        return sqltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.Sqltype
     *
     * @param sqltype the value for FreeHost_SqlProductlist.Sqltype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setSqltype(String sqltype) {
        this.sqltype = sqltype == null ? null : sqltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.Sqlcount
     *
     * @return the value of FreeHost_SqlProductlist.Sqlcount
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getSqlcount() {
        return sqlcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.Sqlcount
     *
     * @param sqlcount the value for FreeHost_SqlProductlist.Sqlcount
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setSqlcount(Integer sqlcount) {
        this.sqlcount = sqlcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.usermoney
     *
     * @return the value of FreeHost_SqlProductlist.usermoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Double getUsermoney() {
        return usermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.usermoney
     *
     * @param usermoney the value for FreeHost_SqlProductlist.usermoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUsermoney(Double usermoney) {
        this.usermoney = usermoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.userspacelimt
     *
     * @return the value of FreeHost_SqlProductlist.userspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getUserspacelimt() {
        return userspacelimt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.userspacelimt
     *
     * @param userspacelimt the value for FreeHost_SqlProductlist.userspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUserspacelimt(Integer userspacelimt) {
        this.userspacelimt = userspacelimt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.logspacelimt
     *
     * @return the value of FreeHost_SqlProductlist.logspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getLogspacelimt() {
        return logspacelimt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.logspacelimt
     *
     * @param logspacelimt the value for FreeHost_SqlProductlist.logspacelimt
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setLogspacelimt(Integer logspacelimt) {
        this.logspacelimt = logspacelimt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.backuptype
     *
     * @return the value of FreeHost_SqlProductlist.backuptype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getBackuptype() {
        return backuptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.backuptype
     *
     * @param backuptype the value for FreeHost_SqlProductlist.backuptype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setBackuptype(Integer backuptype) {
        this.backuptype = backuptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.ServerlistID
     *
     * @return the value of FreeHost_SqlProductlist.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getServerlistid() {
        return serverlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.ServerlistID
     *
     * @param serverlistid the value for FreeHost_SqlProductlist.ServerlistID
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setServerlistid(Integer serverlistid) {
        this.serverlistid = serverlistid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.isbyhost
     *
     * @return the value of FreeHost_SqlProductlist.isbyhost
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getIsbyhost() {
        return isbyhost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.isbyhost
     *
     * @param isbyhost the value for FreeHost_SqlProductlist.isbyhost
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setIsbyhost(String isbyhost) {
        this.isbyhost = isbyhost == null ? null : isbyhost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.Hosttype
     *
     * @return the value of FreeHost_SqlProductlist.Hosttype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getHosttype() {
        return hosttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.Hosttype
     *
     * @param hosttype the value for FreeHost_SqlProductlist.Hosttype
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setHosttype(String hosttype) {
        this.hosttype = hosttype == null ? null : hosttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.cantest
     *
     * @return the value of FreeHost_SqlProductlist.cantest
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCantest() {
        return cantest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.cantest
     *
     * @param cantest the value for FreeHost_SqlProductlist.cantest
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCantest(String cantest) {
        this.cantest = cantest == null ? null : cantest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.canmonth
     *
     * @return the value of FreeHost_SqlProductlist.canmonth
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanmonth() {
        return canmonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.canmonth
     *
     * @param canmonth the value for FreeHost_SqlProductlist.canmonth
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanmonth(String canmonth) {
        this.canmonth = canmonth == null ? null : canmonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.canhalfyear
     *
     * @return the value of FreeHost_SqlProductlist.canhalfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanhalfyear() {
        return canhalfyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.canhalfyear
     *
     * @param canhalfyear the value for FreeHost_SqlProductlist.canhalfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanhalfyear(String canhalfyear) {
        this.canhalfyear = canhalfyear == null ? null : canhalfyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.agent1
     *
     * @return the value of FreeHost_SqlProductlist.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent1() {
        return agent1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.agent1
     *
     * @param agent1 the value for FreeHost_SqlProductlist.agent1
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent1(String agent1) {
        this.agent1 = agent1 == null ? null : agent1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.agent2
     *
     * @return the value of FreeHost_SqlProductlist.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getAgent2() {
        return agent2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.agent2
     *
     * @param agent2 the value for FreeHost_SqlProductlist.agent2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setAgent2(String agent2) {
        this.agent2 = agent2 == null ? null : agent2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.canbyenduser
     *
     * @return the value of FreeHost_SqlProductlist.canbyenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanbyenduser() {
        return canbyenduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.canbyenduser
     *
     * @param canbyenduser the value for FreeHost_SqlProductlist.canbyenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanbyenduser(String canbyenduser) {
        this.canbyenduser = canbyenduser == null ? null : canbyenduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.canbyagnenduser
     *
     * @return the value of FreeHost_SqlProductlist.canbyagnenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanbyagnenduser() {
        return canbyagnenduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.canbyagnenduser
     *
     * @param canbyagnenduser the value for FreeHost_SqlProductlist.canbyagnenduser
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanbyagnenduser(String canbyagnenduser) {
        this.canbyagnenduser = canbyagnenduser == null ? null : canbyagnenduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.canbyagn
     *
     * @return the value of FreeHost_SqlProductlist.canbyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanbyagn() {
        return canbyagn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.canbyagn
     *
     * @param canbyagn the value for FreeHost_SqlProductlist.canbyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanbyagn(String canbyagn) {
        this.canbyagn = canbyagn == null ? null : canbyagn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.orderbyid
     *
     * @return the value of FreeHost_SqlProductlist.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getOrderbyid() {
        return orderbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.orderbyid
     *
     * @param orderbyid the value for FreeHost_SqlProductlist.orderbyid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setOrderbyid(Integer orderbyid) {
        this.orderbyid = orderbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.ServerlistID2
     *
     * @return the value of FreeHost_SqlProductlist.ServerlistID2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getServerlistid2() {
        return serverlistid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.ServerlistID2
     *
     * @param serverlistid2 the value for FreeHost_SqlProductlist.ServerlistID2
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setServerlistid2(Integer serverlistid2) {
        this.serverlistid2 = serverlistid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.ServerlistID3
     *
     * @return the value of FreeHost_SqlProductlist.ServerlistID3
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getServerlistid3() {
        return serverlistid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.ServerlistID3
     *
     * @param serverlistid3 the value for FreeHost_SqlProductlist.ServerlistID3
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setServerlistid3(Integer serverlistid3) {
        this.serverlistid3 = serverlistid3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.ServerlistID4
     *
     * @return the value of FreeHost_SqlProductlist.ServerlistID4
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getServerlistid4() {
        return serverlistid4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.ServerlistID4
     *
     * @param serverlistid4 the value for FreeHost_SqlProductlist.ServerlistID4
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setServerlistid4(Integer serverlistid4) {
        this.serverlistid4 = serverlistid4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.ServerlistID5
     *
     * @return the value of FreeHost_SqlProductlist.ServerlistID5
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getServerlistid5() {
        return serverlistid5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.ServerlistID5
     *
     * @param serverlistid5 the value for FreeHost_SqlProductlist.ServerlistID5
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setServerlistid5(Integer serverlistid5) {
        this.serverlistid5 = serverlistid5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.typeid
     *
     * @return the value of FreeHost_SqlProductlist.typeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.typeid
     *
     * @param typeid the value for FreeHost_SqlProductlist.typeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.canseason
     *
     * @return the value of FreeHost_SqlProductlist.canseason
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanseason() {
        return canseason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.canseason
     *
     * @param canseason the value for FreeHost_SqlProductlist.canseason
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanseason(String canseason) {
        this.canseason = canseason == null ? null : canseason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.updatebytypeid
     *
     * @return the value of FreeHost_SqlProductlist.updatebytypeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getUpdatebytypeid() {
        return updatebytypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.updatebytypeid
     *
     * @param updatebytypeid the value for FreeHost_SqlProductlist.updatebytypeid
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUpdatebytypeid(String updatebytypeid) {
        this.updatebytypeid = updatebytypeid == null ? null : updatebytypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.canupdatespace
     *
     * @return the value of FreeHost_SqlProductlist.canupdatespace
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getCanupdatespace() {
        return canupdatespace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.canupdatespace
     *
     * @param canupdatespace the value for FreeHost_SqlProductlist.canupdatespace
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setCanupdatespace(String canupdatespace) {
        this.canupdatespace = canupdatespace == null ? null : canupdatespace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.updatespacemoney
     *
     * @return the value of FreeHost_SqlProductlist.updatespacemoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public BigDecimal getUpdatespacemoney() {
        return updatespacemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.updatespacemoney
     *
     * @param updatespacemoney the value for FreeHost_SqlProductlist.updatespacemoney
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setUpdatespacemoney(BigDecimal updatespacemoney) {
        this.updatespacemoney = updatespacemoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.PAY_Month
     *
     * @return the value of FreeHost_SqlProductlist.PAY_Month
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPayMonth() {
        return payMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.PAY_Month
     *
     * @param payMonth the value for FreeHost_SqlProductlist.PAY_Month
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPayMonth(String payMonth) {
        this.payMonth = payMonth == null ? null : payMonth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.PAY_Season
     *
     * @return the value of FreeHost_SqlProductlist.PAY_Season
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPaySeason() {
        return paySeason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.PAY_Season
     *
     * @param paySeason the value for FreeHost_SqlProductlist.PAY_Season
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPaySeason(String paySeason) {
        this.paySeason = paySeason == null ? null : paySeason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.PAY_halfyear
     *
     * @return the value of FreeHost_SqlProductlist.PAY_halfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPayHalfyear() {
        return payHalfyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.PAY_halfyear
     *
     * @param payHalfyear the value for FreeHost_SqlProductlist.PAY_halfyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPayHalfyear(String payHalfyear) {
        this.payHalfyear = payHalfyear == null ? null : payHalfyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.PAY_Nextyear
     *
     * @return the value of FreeHost_SqlProductlist.PAY_Nextyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPayNextyear() {
        return payNextyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.PAY_Nextyear
     *
     * @param payNextyear the value for FreeHost_SqlProductlist.PAY_Nextyear
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPayNextyear(String payNextyear) {
        this.payNextyear = payNextyear == null ? null : payNextyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.PAY_2year
     *
     * @return the value of FreeHost_SqlProductlist.PAY_2year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPay2year() {
        return pay2year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.PAY_2year
     *
     * @param pay2year the value for FreeHost_SqlProductlist.PAY_2year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPay2year(String pay2year) {
        this.pay2year = pay2year == null ? null : pay2year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.PAY_3year
     *
     * @return the value of FreeHost_SqlProductlist.PAY_3year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPay3year() {
        return pay3year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.PAY_3year
     *
     * @param pay3year the value for FreeHost_SqlProductlist.PAY_3year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPay3year(String pay3year) {
        this.pay3year = pay3year == null ? null : pay3year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.PAY_4year
     *
     * @return the value of FreeHost_SqlProductlist.PAY_4year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPay4year() {
        return pay4year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.PAY_4year
     *
     * @param pay4year the value for FreeHost_SqlProductlist.PAY_4year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPay4year(String pay4year) {
        this.pay4year = pay4year == null ? null : pay4year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.PAY_5year
     *
     * @return the value of FreeHost_SqlProductlist.PAY_5year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getPay5year() {
        return pay5year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.PAY_5year
     *
     * @param pay5year the value for FreeHost_SqlProductlist.PAY_5year
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setPay5year(String pay5year) {
        this.pay5year = pay5year == null ? null : pay5year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FreeHost_SqlProductlist.onlyusebyagn
     *
     * @return the value of FreeHost_SqlProductlist.onlyusebyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public String getOnlyusebyagn() {
        return onlyusebyagn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FreeHost_SqlProductlist.onlyusebyagn
     *
     * @param onlyusebyagn the value for FreeHost_SqlProductlist.onlyusebyagn
     *
     * @mbg.generated Fri May 11 11:16:07 CST 2018
     */
    public void setOnlyusebyagn(String onlyusebyagn) {
        this.onlyusebyagn = onlyusebyagn == null ? null : onlyusebyagn.trim();
    }
}